<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Orlando Joaqui-Barandica">
<meta name="dcterms.date" content="2025-09-07">

<title>Toma de Decisiones Basadas en Datos - Regresión Cuantil</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Toma de Decisiones Basadas en Datos</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Inicio</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#materiales" id="toc-materiales" class="nav-link active" data-scroll-target="#materiales"><span class="header-section-number">1</span> Materiales</a></li>
  <li><a href="#resumen-de-la-sesión" id="toc-resumen-de-la-sesión" class="nav-link" data-scroll-target="#resumen-de-la-sesión"><span class="header-section-number">2</span> Resumen de la sesión</a></li>
  <li><a href="#objetivos-de-aprendizaje" id="toc-objetivos-de-aprendizaje" class="nav-link" data-scroll-target="#objetivos-de-aprendizaje"><span class="header-section-number">3</span> Objetivos de aprendizaje</a></li>
  <li><a href="#marco-conceptual" id="toc-marco-conceptual" class="nav-link" data-scroll-target="#marco-conceptual"><span class="header-section-number">4</span> Marco conceptual</a>
  <ul class="collapse">
  <li><a href="#elección-binaria-y-modelo-logit" id="toc-elección-binaria-y-modelo-logit" class="nav-link" data-scroll-target="#elección-binaria-y-modelo-logit"><span class="header-section-number">4.1</span> Elección binaria y modelo Logit</a></li>
  <li><a href="#de-binario-a-multinomial" id="toc-de-binario-a-multinomial" class="nav-link" data-scroll-target="#de-binario-a-multinomial"><span class="header-section-number">4.2</span> De binario a multinomial</a></li>
  </ul></li>
  <li><a href="#codigo-modelo-logit---probit" id="toc-codigo-modelo-logit---probit" class="nav-link" data-scroll-target="#codigo-modelo-logit---probit"><span class="header-section-number">5</span> Codigo Modelo Logit - Probit</a>
  <ul class="collapse">
  <li><a href="#hosmer-lemeshow" id="toc-hosmer-lemeshow" class="nav-link" data-scroll-target="#hosmer-lemeshow"><span class="header-section-number">5.1</span> Hosmer-Lemeshow</a></li>
  <li><a href="#modelo-probit" id="toc-modelo-probit" class="nav-link" data-scroll-target="#modelo-probit"><span class="header-section-number">5.2</span> Modelo Probit</a></li>
  <li><a href="#modelo-multinomial" id="toc-modelo-multinomial" class="nav-link" data-scroll-target="#modelo-multinomial"><span class="header-section-number">5.3</span> Modelo Multinomial</a></li>
  </ul></li>
  <li><a href="#taller" id="toc-taller" class="nav-link" data-scroll-target="#taller"><span class="header-section-number">6</span> Taller</a>
  <ul class="collapse">
  <li><a href="#objetivo" id="toc-objetivo" class="nav-link" data-scroll-target="#objetivo"><span class="header-section-number">6.1</span> Objetivo</a></li>
  <li><a href="#fuentes-sugeridas" id="toc-fuentes-sugeridas" class="nav-link" data-scroll-target="#fuentes-sugeridas"><span class="header-section-number">6.2</span> Fuentes sugeridas</a></li>
  <li><a href="#ejemplos-de-preguntas" id="toc-ejemplos-de-preguntas" class="nav-link" data-scroll-target="#ejemplos-de-preguntas"><span class="header-section-number">6.3</span> Ejemplos de preguntas</a></li>
  <li><a href="#pasos-mínimos" id="toc-pasos-mínimos" class="nav-link" data-scroll-target="#pasos-mínimos"><span class="header-section-number">6.4</span> Pasos (mínimos)</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Regresión Cuantil</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Orlando Joaqui-Barandica </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 7, 2025</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="materiales" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Materiales</h1>
<ul>
<li>R ≥ 4.1 y paquetes: <code>quantreg</code>, <code>ggplot2</code>, <code>dplyr</code>, <code>AER</code>, <code>broom</code>, <code>purrr</code>, <code>tidyr</code>, <code>scales</code>.</li>
<li>Dataset de ejemplo: <code>AER::CPS1985</code> (salarios en EE. UU. 1985).</li>
</ul>
</section>
<section id="resumen-de-la-sesión" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Resumen de la sesión</h1>
<p>En esta sesión introducimos <strong>modelos de elección discreta</strong> para variables dependientes cualitativas. Empezamos con casos binarios y el <strong>modelo Logit</strong> (formulación, interpretación y validación) y avanzamos a elecciones con <strong>m&gt;2</strong> alternativas mediante <strong>Logit Multinomial</strong>. Cerraremos con criterios para decidir entre <strong>binario, multinomial u ordinal</strong> y simulaciones reproducibles (código oculto).</p>
</section>
<section id="objetivos-de-aprendizaje" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Objetivos de aprendizaje</h1>
<ul>
<li>Distinguir entre variables <strong>binarias, ordinales y nominales</strong> y seleccionar el modelo adecuado.</li>
<li>Formular e interpretar un <strong>Logit</strong> (odds, OR, efectos marginales y ajuste).</li>
<li>Entender la teoría de <strong>utilidad aleatoria</strong> y la especificación del <strong>Logit Multinomial</strong>.</li>
<li>Reconocer cuándo usar <strong>modelos ordinales</strong> (líneas paralelas) vs <strong>multinomiales</strong>.</li>
</ul>
</section>
<section id="marco-conceptual" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Marco conceptual</h1>
<p>Los <strong>modelos de elección discreta</strong> estudian la probabilidad de que un individuo elija una opción dentro de un conjunto finito. Ejemplos:</p>
<ul>
<li><ol type="i">
<li><strong>Adopción de un crédito</strong> (sí/no)</li>
</ol></li>
<li><ol start="2" type="i">
<li><strong>Compra online</strong> (sí/no)</li>
</ol></li>
<li><ol start="3" type="i">
<li><strong>Modo de transporte</strong> (bus/auto/bici)</li>
</ol></li>
<li><ol start="4" type="i">
<li><strong>Elección de marca</strong> (m&gt;2, nominal)</li>
</ol></li>
<li><ol start="22" type="a">
<li><strong>Satisfacción</strong> en escalas Likert (ordinal).</li>
</ol></li>
</ul>
<section id="elección-binaria-y-modelo-logit" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="elección-binaria-y-modelo-logit"><span class="header-section-number">4.1</span> Elección binaria y modelo Logit</h2>
<p>Sea <span class="math inline">\((Y_i \in {0,1})\)</span>. El <strong>Logit</strong> modela <span class="math inline">\((p_i=Pr(Y_i=1\mid X_i))\)</span> con</p>
<p><span class="math display">\[ p_i=\frac{1}{1+e^{-X_i'\beta}} \quad \Rightarrow \quad \log\frac{p_i}{1-p_i}=X_i'\beta. \]</span></p>
<p>Se estima por máxima verosimilitud; los coeficientes se interpretan como odds ratios <span class="math inline">\((\exp(\beta_j))\)</span>; los efectos en probabilidad mediante <strong>efectos marginales</strong>.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Cuándo usar Logit (binario):</strong> cuando la respuesta tiene 2 categorías excluyentes y nos interesa modelar <strong>probabilidades</strong> acotadas en <span class="math inline">\((0,1)\)</span> con elasticidad no lineal. Evita el <strong>MLP</strong> por predicciones fuera de <span class="math inline">\((0,1)\)</span>, heterocedasticidad y linealidad estricta.</p>
</div>
</div>
</section>
<section id="de-binario-a-multinomial" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="de-binario-a-multinomial"><span class="header-section-number">4.2</span> De binario a multinomial</h2>
<p>Cuando <span class="math inline">\((m&gt;2)\)</span> sin orden, partimos de <strong>utilidad aleatoria</strong>:</p>
<p>El individuo (i) elige la alternativa (j) con mayor utilidad</p>
<p><span class="math display">\[(U_{ij}=X_i'\beta_j+\varepsilon_{ij})\]</span>.</p>
<p>Con errores i.i.d. se deriva el <strong>Logit Multinomial</strong> (base category logit):</p>
<p><span class="math display">\[Pr(Y_i=j\mid X_i)=\frac{\exp(X_i'\beta_j)}{\sum_{h=0}^{m-1}\exp(X_i'\beta_h)},\]</span></p>
<p>Relación con múltiples logits binarios y eficiencia de estimar <strong>simultáneamente</strong> (vs.&nbsp;pares por separado). Considere el supuesto <strong>IIA</strong> (independencia de alternativas irrelevantes) y sus implicaciones empíricas.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>¿Multinomial u ordinal?</strong> Si las categorías tienen <strong>orden</strong> (p.&nbsp;ej., <em>baja, media, alta</em>), prefiera <strong>logit/probit ordinal</strong> (líneas paralelas). Usar un modelo nominal sobre datos ordinales pierde eficiencia; usar un ordinal sobre datos nominales introduce <strong>sesgo</strong>.</p>
</div>
</div>
</section>
</section>
<section id="codigo-modelo-logit---probit" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Codigo Modelo Logit - Probit</h1>
<p>Un investigador está interesado en cómo las variables, como el GRE (puntaje del examen de Graduados), el GPA (promedio de calificaciones) y el prestigio de la institución de pregrado, tienen efecto en la admisión a la escuela de postgrado.</p>
<blockquote class="blockquote">
<p>La variable de respuesta, admitir / no admitir, es una variable binaria.</p>
</blockquote>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">######################################</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Modelo Logit - Probit</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="do">######################################</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>mydata <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Datos/binary.csv"</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mydata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["admit"],"name":[1],"type":["int"],"align":["right"]},{"label":["gre"],"name":[2],"type":["int"],"align":["right"]},{"label":["gpa"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["rank"],"name":[4],"type":["int"],"align":["right"]}],"data":[{"1":"0","2":"380","3":"3.61","4":"3","_rn_":"1"},{"1":"1","2":"660","3":"3.67","4":"3","_rn_":"2"},{"1":"1","2":"800","3":"4.00","4":"1","_rn_":"3"},{"1":"1","2":"640","3":"3.19","4":"4","_rn_":"4"},{"1":"0","2":"520","3":"2.93","4":"4","_rn_":"5"},{"1":"1","2":"760","3":"3.00","4":"2","_rn_":"6"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mydata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     admit             gre             gpa             rank      
 Min.   :0.0000   Min.   :220.0   Min.   :2.260   Min.   :1.000  
 1st Qu.:0.0000   1st Qu.:520.0   1st Qu.:3.130   1st Qu.:2.000  
 Median :0.0000   Median :580.0   Median :3.395   Median :2.000  
 Mean   :0.3175   Mean   :587.7   Mean   :3.390   Mean   :2.485  
 3rd Qu.:1.0000   3rd Qu.:660.0   3rd Qu.:3.670   3rd Qu.:3.000  
 Max.   :1.0000   Max.   :800.0   Max.   :4.000   Max.   :4.000  </code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(mydata, sd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      admit         gre         gpa        rank 
  0.4660867 115.5165364   0.3805668   0.9444602 </code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xtabs</span>(<span class="sc">~</span>admit <span class="sc">+</span> rank, <span class="at">data =</span> mydata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     rank
admit  1  2  3  4
    0 28 97 93 55
    1 33 54 28 12</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># MODELO LOGIT </span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>mydata<span class="sc">$</span>rank <span class="ot">&lt;-</span> <span class="fu">factor</span>(mydata<span class="sc">$</span>rank)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>mylogit <span class="ot">&lt;-</span> <span class="fu">glm</span>(admit <span class="sc">~</span> gre <span class="sc">+</span> gpa <span class="sc">+</span> rank, <span class="at">data =</span> mydata, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mylogit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = admit ~ gre + gpa + rank, family = "binomial", 
    data = mydata)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.6268  -0.8662  -0.6388   1.1490   2.0790  

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -3.989979   1.139951  -3.500 0.000465 ***
gre          0.002264   0.001094   2.070 0.038465 *  
gpa          0.804038   0.331819   2.423 0.015388 *  
rank2       -0.675443   0.316490  -2.134 0.032829 *  
rank3       -1.340204   0.345306  -3.881 0.000104 ***
rank4       -1.551464   0.417832  -3.713 0.000205 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 499.98  on 399  degrees of freedom
Residual deviance: 458.52  on 394  degrees of freedom
AIC: 470.52

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>Tanto gre como gpa son estadísticamente significativos, al igual que los tres términos para rango. Los coeficientes de regresión logística dan el cambio en las probabilidades del logaritmo del resultado para un aumento de una unidad en la variable predictora.</p>
<ul>
<li>Por cada cambio de unidades en gre, las probabilidades log de admisión (versus no admisión) aumentan en 0.002.</li>
<li>Para un aumento de una unidad en gpa, las probabilidades de registro de admisión a la escuela de posgrado aumenta en 0,804.</li>
<li>Las variables indicadoras de rango tienen una interpretación ligeramente diferente.</li>
<li>Por ejemplo, haber asistido a una institución de pregrado con un rango de 2, frente a una institución con un rango de 1,cambia las probabilidades de registro de admisión en -0.675.</li>
<li>Debajo de la tabla de coeficientes se encuentran los índices de ajuste, incluidos los residuales nulos y de desviación y el AIC.</li>
<li>Más adelante mostramos un ejemplo de cómo puede usar estos valores para ayudar a evaluar el ajuste del modelo.</li>
</ul>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mylogit) <span class="co"># Usando Max. Verosimilitud</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                    2.5 %       97.5 %
(Intercept) -6.2716202334 -1.792547080
gre          0.0001375921  0.004435874
gpa          0.1602959439  1.464142727
rank2       -1.3008888002 -0.056745722
rank3       -2.0276713127 -0.670372346
rank4       -2.4000265384 -0.753542605</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint.default</span>(mylogit) <span class="co">#Usando errores estándar</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                    2.5 %       97.5 %
(Intercept) -6.2242418514 -1.755716295
gre          0.0001202298  0.004408622
gpa          0.1536836760  1.454391423
rank2       -1.2957512650 -0.055134591
rank3       -2.0169920597 -0.663415773
rank4       -2.3703986294 -0.732528724</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(mylogit)) <span class="co"># Odds ratios</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         gre         gpa       rank2       rank3       rank4 
  0.0185001   1.0022670   2.2345448   0.5089310   0.2617923   0.2119375 </code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="at">OR =</span> <span class="fu">coef</span>(mylogit), <span class="fu">confint</span>(mylogit))) <span class="co"># Odds ratios - Int. Conf.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                   OR       2.5 %    97.5 %
(Intercept) 0.0185001 0.001889165 0.1665354
gre         1.0022670 1.000137602 1.0044457
gpa         2.2345448 1.173858216 4.3238349
rank2       0.5089310 0.272289674 0.9448343
rank3       0.2617923 0.131641717 0.5115181
rank4       0.2119375 0.090715546 0.4706961</code></pre>
</div>
</div>
<p>Ahora podemos decir que para un aumento de una unidad en gpa, las probabilidades de ser admitido en la escuela de postgrado (versus no ser admitido) aumentan en un factor de 2.23.</p>
<p>También puede usar las probabilidades pronosticadas para ayudarlo a comprender el modelo. Las probabilidades pronosticadas se pueden calcular para variables predictoras tanto categóricas como continuas. Para crear probabilidades pronosticadas, primero necesitamos crear un nuevo marco de datos con los valores que queremos que las variables independientes adopten para crear nuestras predicciones.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>newdata1 <span class="ot">&lt;-</span> <span class="fu">with</span>(mydata, <span class="fu">data.frame</span>(<span class="at">gre =</span> <span class="fu">mean</span>(gre), <span class="at">gpa =</span> <span class="fu">mean</span>(gpa), <span class="at">rank =</span> <span class="fu">factor</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>)))</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>newdata1<span class="sc">$</span>rankP <span class="ot">&lt;-</span> <span class="fu">predict</span>(mylogit, <span class="at">newdata =</span> newdata1, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>newdata1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["gre"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["gpa"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["rank"],"name":[3],"type":["fct"],"align":["left"]},{"label":["rankP"],"name":[4],"type":["dbl"],"align":["right"]}],"data":[{"1":"587.7","2":"3.3899","3":"1","4":"0.5166016"},{"1":"587.7","2":"3.3899","3":"2","4":"0.3522846"},{"1":"587.7","2":"3.3899","3":"3","4":"0.2186120"},{"1":"587.7","2":"3.3899","3":"4","4":"0.1846684"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>En el resultado anterior, vemos que la probabilidad prevista de ser aceptado en un programa de postgrado es de 0.52 para estudiantes de las instituciones de pregrado de mayor prestigio (rango = 1) y 0.18 para estudiantes de las instituciones de menor rango (rango = 4), con gre y gpa por sus valores medios. Podemos hacer algo muy similar para crear una tabla de probabilidades predichas que varíe el valor de gre y rank. Vamos a trazarlos, por lo que crearemos 100 valores de gre entre 200 y 800, en cada valor de rango (es decir, 1, 2, 3 y 4).</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>newdata2 <span class="ot">&lt;-</span> <span class="fu">with</span>(mydata, <span class="fu">data.frame</span>(<span class="at">gre =</span> <span class="fu">rep</span>(<span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">200</span>, <span class="at">to =</span> <span class="dv">800</span>, <span class="at">length.out =</span> <span class="dv">100</span>),<span class="dv">4</span>), </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">gpa =</span> <span class="fu">mean</span>(gpa), <span class="at">rank =</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">each =</span> <span class="dv">100</span>))))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>El código para generar las probabilidades predichas (la primera línea a continuación) es el mismo que antes, excepto que también vamos a pedir errores estándar para que podamos trazar un intervalo de confianza. Obtenemos las estimaciones en la escala del enlace y transformamos los valores pronosticados y los límites de confianza en probabilidades.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>newdata3 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(newdata2, <span class="fu">predict</span>(mylogit, <span class="at">newdata =</span> newdata2, <span class="at">type =</span> <span class="st">"link"</span>,</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">se =</span> <span class="cn">TRUE</span>))</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>newdata3 <span class="ot">&lt;-</span> <span class="fu">within</span>(newdata3, {</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  PredictedProb <span class="ot">&lt;-</span> <span class="fu">plogis</span>(fit)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  LL <span class="ot">&lt;-</span> <span class="fu">plogis</span>(fit <span class="sc">-</span> (<span class="fl">1.96</span> <span class="sc">*</span> se.fit))</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  UL <span class="ot">&lt;-</span> <span class="fu">plogis</span>(fit <span class="sc">+</span> (<span class="fl">1.96</span> <span class="sc">*</span> se.fit))</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(newdata3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["gre"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["gpa"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["rank"],"name":[3],"type":["fct"],"align":["left"]},{"label":["fit"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["se.fit"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["residual.scale"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["UL"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["LL"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["PredictedProb"],"name":[9],"type":["dbl"],"align":["right"]}],"data":[{"1":"200.0000","2":"3.3899","3":"1","4":"-0.8114870","5":"0.5147714","6":"1","7":"0.5492064","8":"0.1393812","9":"0.3075737","_rn_":"1"},{"1":"206.0606","2":"3.3899","3":"1","4":"-0.7977632","5":"0.5090986","6":"1","7":"0.5498513","8":"0.1423880","9":"0.3105042","_rn_":"2"},{"1":"212.1212","2":"3.3899","3":"1","4":"-0.7840394","5":"0.5034491","6":"1","7":"0.5505074","8":"0.1454429","9":"0.3134499","_rn_":"3"},{"1":"218.1818","2":"3.3899","3":"1","4":"-0.7703156","5":"0.4978239","6":"1","7":"0.5511750","8":"0.1485460","9":"0.3164108","_rn_":"4"},{"1":"224.2424","2":"3.3899","3":"1","4":"-0.7565919","5":"0.4922237","6":"1","7":"0.5518545","8":"0.1516973","9":"0.3193867","_rn_":"5"},{"1":"230.3030","2":"3.3899","3":"1","4":"-0.7428681","5":"0.4866494","6":"1","7":"0.5525464","8":"0.1548966","9":"0.3223773","_rn_":"6"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(newdata3, <span class="fu">aes</span>(<span class="at">x =</span> gre, <span class="at">y =</span> PredictedProb)) <span class="sc">+</span> </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> LL,<span class="at">ymax =</span> UL, <span class="at">fill =</span> rank), <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">colour =</span> rank),<span class="at">size =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="clase05_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="hosmer-lemeshow" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="hosmer-lemeshow"><span class="header-section-number">5.1</span> Hosmer-Lemeshow</h2>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ResourceSelection)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hoslem.test</span>(mylogit<span class="sc">$</span>y,<span class="fu">fitted</span>(mylogit))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Hosmer and Lemeshow goodness of fit (GOF) test

data:  mylogit$y, fitted(mylogit)
X-squared = 11.085, df = 8, p-value = 0.1969</code></pre>
</div>
</div>
<p>No rechazo Ho, indicando que no hay evidencia de mal ajuste. Esto es bueno, ya que aquí sabemos que el modelo está correctamente especificado.</p>
</section>
<section id="modelo-probit" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="modelo-probit"><span class="header-section-number">5.2</span> Modelo Probit</h2>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># MODELO PROBIT</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>myprobit <span class="ot">&lt;-</span> <span class="fu">glm</span>(admit <span class="sc">~</span> gre <span class="sc">+</span> gpa <span class="sc">+</span> rank, <span class="at">data =</span> mydata, <span class="at">family =</span>  <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"probit"</span>))</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(myprobit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = admit ~ gre + gpa + rank, family = binomial(link = "probit"), 
    data = mydata)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.6163  -0.8710  -0.6389   1.1560   2.1035  

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -2.386836   0.673946  -3.542 0.000398 ***
gre          0.001376   0.000650   2.116 0.034329 *  
gpa          0.477730   0.197197   2.423 0.015410 *  
rank2       -0.415399   0.194977  -2.131 0.033130 *  
rank3       -0.812138   0.208358  -3.898 9.71e-05 ***
rank4       -0.935899   0.245272  -3.816 0.000136 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 499.98  on 399  degrees of freedom
Residual deviance: 458.41  on 394  degrees of freedom
AIC: 470.41

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Hosmer-Lemeshow</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ResourceSelection)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="fu">hoslem.test</span>(myprobit<span class="sc">$</span>y,<span class="fu">fitted</span>(myprobit))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Hosmer and Lemeshow goodness of fit (GOF) test

data:  myprobit$y, fitted(myprobit)
X-squared = 12.609, df = 8, p-value = 0.126</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparación de Modelos</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(memisc)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mtable</span>(myprobit, mylogit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Calls:
myprobit: glm(formula = admit ~ gre + gpa + rank, family = binomial(link = "probit"), 
    data = mydata)
mylogit: glm(formula = admit ~ gre + gpa + rank, family = "binomial", 
    data = mydata)

============================================
                   myprobit      mylogit    
--------------------------------------------
  (Intercept)       -2.387***    -3.990***  
                    (0.674)      (1.140)    
  gre                0.001*       0.002*    
                    (0.001)      (0.001)    
  gpa                0.478*       0.804*    
                    (0.197)      (0.332)    
  rank: 2/1         -0.415*      -0.675*    
                    (0.195)      (0.316)    
  rank: 3/1         -0.812***    -1.340***  
                    (0.208)      (0.345)    
  rank: 4/1         -0.936***    -1.551***  
                    (0.245)      (0.418)    
--------------------------------------------
  Log-likelihood  -229.207     -229.259     
  N                400          400         
============================================
  Significance: *** = p &lt; 0.001;   
                ** = p &lt; 0.01;   
                * = p &lt; 0.05  </code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(marginaleffects)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="fu">avg_slopes</span>(mylogit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["term"],"name":[1],"type":["chr"],"align":["left"]},{"label":["contrast"],"name":[2],"type":["chr"],"align":["left"]},{"label":["estimate"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["std.error"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["statistic"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["p.value"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["s.value"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["conf.low"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["conf.high"],"name":[9],"type":["dbl"],"align":["right"]}],"data":[{"1":"gpa","2":"dY/dX","3":"0.1564373034","4":"0.062970256","5":"2.484305","6":"1.298047e-02","7":"6.267514","8":"3.301787e-02","9":"0.2798567374"},{"1":"gre","2":"dY/dX","3":"0.0004405767","4":"0.000209123","5":"2.106783","6":"3.513641e-02","7":"4.830889","8":"3.070319e-05","9":"0.0008504502"},{"1":"rank","2":"2 - 1","3":"-0.1566044016","4":"0.073618683","5":"-2.127237","6":"3.340038e-02","7":"4.903992","8":"-3.008944e-01","9":"-0.0123144350"},{"1":"rank","2":"3 - 1","3":"-0.2872231506","4":"0.073327833","5":"-3.916973","6":"8.966775e-05","7":"13.445051","8":"-4.309431e-01","9":"-0.1435032386"},{"1":"rank","2":"4 - 1","3":"-0.3212383134","4":"0.080205007","5":"-4.005215","6":"6.196105e-05","7":"13.978279","8":"-4.784372e-01","9":"-0.1640393883"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Esto me permite cuantificar el cambio promedio en la probabilidad de admisión (admit) asociado con cambios unitarios en las variables explicativas (gre, gpa y rank), proporcionando una interpretación más clara de los efectos directos de cada variable en la probabilidad de admisión.</p>
<p>En este bloque de código, estoy ajustando un modelo de regresión logística (logit) para predecir la probabilidad de admisión (admit) en función del puntaje GRE, el GPA, el rango de la institución de pregrado (rank) y la interacción entre GRE y GPA.</p>
<p>Luego, utilizo la función plot_slopes para visualizar cómo varía la pendiente de la probabilidad de admisión en función de GRE condicionado al GPA y viceversa. Esto me permite entender mejor la interacción entre GRE y GPA y su efecto en la probabilidad de admisión.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>mylogit2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(admit <span class="sc">~</span> gre <span class="sc">+</span> gpa <span class="sc">+</span> gre<span class="sc">*</span>gpa <span class="sc">+</span> rank, <span class="at">data =</span> mydata, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Graficar la pendiente del efecto de GRE en la probabilidad de admisión condicionada al GPA</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_slopes</span>(mylogit2, <span class="at">variables=</span><span class="st">"gre"</span>, <span class="at">condition =</span> <span class="st">"gpa"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="clase05_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Graficar la pendiente del efecto de GPA en la probabilidad de admisión condicionada al GRE</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_slopes</span>(mylogit2, <span class="at">variables=</span><span class="st">"gpa"</span>, <span class="at">condition =</span> <span class="st">"gre"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="clase05_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid" width="672"></p>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ahora con la variable rank</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>mylogit2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(admit <span class="sc">~</span> gre <span class="sc">+</span> gpa <span class="sc">+</span> rank<span class="sc">*</span>gpa <span class="sc">+</span> rank, <span class="at">data =</span> mydata, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_slopes</span>(mylogit2, <span class="at">variables=</span><span class="st">"rank"</span>, <span class="at">condition =</span> <span class="st">"gpa"</span>)<span class="sc">+</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lims</span>(<span class="at">y=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="clase05_files/figure-html/unnamed-chunk-9-3.png" class="img-fluid" width="672"></p>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>mylogit2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(admit <span class="sc">~</span> gre <span class="sc">+</span> gpa <span class="sc">+</span> rank<span class="sc">*</span>gre <span class="sc">+</span> rank, <span class="at">data =</span> mydata, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_slopes</span>(mylogit2, <span class="at">variables=</span><span class="st">"rank"</span>, <span class="at">condition =</span> <span class="st">"gre"</span>)<span class="sc">+</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lims</span>(<span class="at">y=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="clase05_files/figure-html/unnamed-chunk-9-4.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="modelo-multinomial" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="modelo-multinomial"><span class="header-section-number">5.3</span> Modelo Multinomial</h2>
<blockquote class="blockquote">
<p>Ejemplo 1. Las elecciones ocupacionales de las personas pueden verse influenciadas por las ocupaciones de sus padres y su propio nivel educativo. Podemos estudiar la relación entre la elección de ocupación y el nivel educativo y la ocupación del padre. Las elecciones ocupacionales serán la variable de resultado que consta de categorías de ocupaciones.</p>
</blockquote>
<blockquote class="blockquote">
<p>Ejemplo 2. Un biólogo puede estar interesado en las elecciones de alimentos que hacen los caimanes. Los caimanes adultos pueden tener preferencias diferentes a las de los jóvenes. La variable de resultado aquí serán los tipos de alimentos, y las variables predictoras podrían ser el tamaño de los caimanes y otras variables ambientales.</p>
</blockquote>
<blockquote class="blockquote">
<p>Ejemplo 3. Los estudiantes que ingresan a la escuela secundaria eligen programas entre programa general, programa vocacional y programa académico. Su elección podría modelarse utilizando su puntaje de escritura y su estatus económico social.</p>
</blockquote>
<p>El conjunto de datos contiene variables sobre 200 estudiantes. La variable de resultado es ‘prog’ tipo de programa. Las variables predictoras son el status socioeconómico, ‘ses’ una variable categórica de tres niveles, y la puntuación de escritura, ‘write’ una variable continua.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="do">######################################</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Modelo Multinomial</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="do">######################################</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(foreign) </span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nnet) </span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2) </span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>ml  <span class="ot">&lt;-</span>  <span class="fu">read.dta</span> ( <span class="st">"Datos/hsb.dta"</span> )</span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ml)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["id"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["female"],"name":[2],"type":["fct"],"align":["left"]},{"label":["ses"],"name":[3],"type":["fct"],"align":["left"]},{"label":["schtyp"],"name":[4],"type":["fct"],"align":["left"]},{"label":["prog"],"name":[5],"type":["fct"],"align":["left"]},{"label":["read"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["write"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["math"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["science"],"name":[9],"type":["dbl"],"align":["right"]},{"label":["socst"],"name":[10],"type":["dbl"],"align":["right"]},{"label":["honors"],"name":[11],"type":["fct"],"align":["left"]},{"label":["awards"],"name":[12],"type":["dbl"],"align":["right"]},{"label":["cid"],"name":[13],"type":["int"],"align":["right"]}],"data":[{"1":"45","2":"female","3":"low","4":"public","5":"vocation","6":"34","7":"35","8":"41","9":"29","10":"26","11":"not enrolled","12":"0","13":"1","_rn_":"1"},{"1":"108","2":"male","3":"middle","4":"public","5":"general","6":"34","7":"33","8":"41","9":"36","10":"36","11":"not enrolled","12":"0","13":"1","_rn_":"2"},{"1":"15","2":"male","3":"high","4":"public","5":"vocation","6":"39","7":"39","8":"44","9":"26","10":"42","11":"not enrolled","12":"0","13":"1","_rn_":"3"},{"1":"67","2":"male","3":"low","4":"public","5":"vocation","6":"37","7":"37","8":"42","9":"33","10":"32","11":"not enrolled","12":"0","13":"1","_rn_":"4"},{"1":"153","2":"male","3":"middle","4":"public","5":"vocation","6":"39","7":"31","8":"40","9":"39","10":"51","11":"not enrolled","12":"0","13":"1","_rn_":"5"},{"1":"51","2":"female","3":"high","4":"public","5":"general","6":"42","7":"36","8":"42","9":"31","10":"39","11":"not enrolled","12":"0","13":"1","_rn_":"6"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>A continuación utilizamos la función multinom del nnet paquete para estimar un modelo de regresión logística multinomial. Hay otras funciones en otros paquetes de R capaces de realizar regresión multinomial.</p>
<p>Primero, debemos elegir el nivel de nuestro resultado que deseamos utilizar como línea de base y especificarlo en la función relevel. Luego, ejecutamos nuestro modelo usando multinom. El paquete multinom no incluye el cálculo del valor p para los coeficientes de regresión, por lo que calculamos los valores p utilizando las pruebas de Wald (aquí pruebas z).</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>ml<span class="sc">$</span>prog2 <span class="ot">&lt;-</span> <span class="fu">relevel</span>(ml<span class="sc">$</span>prog, <span class="at">ref =</span> <span class="st">"academic"</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> <span class="fu">multinom</span>(prog2 <span class="sc">~</span> ses <span class="sc">+</span> write, <span class="at">data =</span> ml)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># weights:  15 (8 variable)
initial  value 219.722458 
iter  10 value 179.982880
final  value 179.981726 
converged</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
multinom(formula = prog2 ~ ses + write, data = ml)

Coefficients:
         (Intercept)  sesmiddle    seshigh      write
general     2.852198 -0.5332810 -1.1628226 -0.0579287
vocation    5.218260  0.2913859 -0.9826649 -0.1136037

Std. Errors:
         (Intercept) sesmiddle   seshigh      write
general     1.166441 0.4437323 0.5142196 0.02141097
vocation    1.163552 0.4763739 0.5955665 0.02221996

Residual Deviance: 359.9635 
AIC: 375.9635 </code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Valores z</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">summary</span>(test)<span class="sc">$</span>coefficients<span class="sc">/</span><span class="fu">summary</span>(test)<span class="sc">$</span>standard.errors</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>z</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>         (Intercept)  sesmiddle   seshigh     write
general     2.445214 -1.2018081 -2.261334 -2.705562
vocation    4.484769  0.6116747 -1.649967 -5.112689</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Valores p</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(z), <span class="dv">0</span>, <span class="dv">1</span>)) <span class="sc">*</span> <span class="dv">2</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>p</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>          (Intercept) sesmiddle    seshigh        write
general  0.0144766100 0.2294379 0.02373856 6.818902e-03
vocation 0.0000072993 0.5407530 0.09894976 3.176045e-07</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Algunas interpretaciones del modelo "test"</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
multinom(formula = prog2 ~ ses + write, data = ml)

Coefficients:
         (Intercept)  sesmiddle    seshigh      write
general     2.852198 -0.5332810 -1.1628226 -0.0579287
vocation    5.218260  0.2913859 -0.9826649 -0.1136037

Std. Errors:
         (Intercept) sesmiddle   seshigh      write
general     1.166441 0.4437323 0.5142196 0.02141097
vocation    1.163552 0.4763739 0.5955665 0.02221996

Residual Deviance: 359.9635 
AIC: 375.9635 </code></pre>
</div>
</div>
<ul>
<li><p>Un aumento de una unidad en la variable write se asocia con una disminución en las probabilidades logarítmicas de estar en un programa general versus un programa académico en una cantidad de 0,058.</p></li>
<li><p>Un aumento de una unidad en la variable write se asocia con la disminución en las probabilidades logarítmicas de estar en un programa vocacional versus un programa académico. por la cantidad de .1136</p></li>
<li><p>Las probabilidades logarítmicas de estar en un programa general frente a un programa académico disminuirán en 1.163 si se pasa de ses=“low”a ses=“high”</p></li>
<li><p>Las probabilidades logarítmicas de estar en un programa general frente a un programa académico disminuirán en 0.533 si se pasa de ses=“low”a ses=“middle”, aunque este coeficiente no es significativo.</p></li>
<li><p>Las probabilidades logarítmicas de estar en un programa vocacional frente a un programa académico disminuirán en 0.983 si se pasa de ses=“low”a ses=“high”</p></li>
<li><p>Las probabilidades logarítmicas de estar en un programa vocacional frente a un programa académico aumentarán en 0.291 si se pasa de ses=“low”a ses=“middle”,aunque este coeficiente no es significativo.</p></li>
</ul>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Odds ratio</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(test))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>         (Intercept) sesmiddle   seshigh     write
general     17.32582 0.5866769 0.3126026 0.9437172
vocation   184.61262 1.3382809 0.3743123 0.8926116</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Probabilidades predichas</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>pp <span class="ot">&lt;-</span> <span class="fu">fitted</span>(test)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>pp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     academic    general   vocation
1   0.1482764 0.33824545 0.51347812
2   0.1202017 0.18062830 0.69916997
3   0.4186747 0.23680818 0.34451707
4   0.1726885 0.35083838 0.47647308
5   0.1001231 0.16893737 0.73093949
6   0.3533566 0.23779760 0.40884583
7   0.1562562 0.19735040 0.64639339
8   0.1001231 0.16893737 0.73093949
9   0.2331292 0.22039757 0.54647324
10  0.1699402 0.20255307 0.62750669
11  0.2777727 0.37620656 0.34602073
12  0.2917502 0.23360371 0.47464612
13  0.1071687 0.30821953 0.58461179
14  0.2888779 0.22953567 0.48158639
15  0.1482764 0.33824545 0.51347812
16  0.2777727 0.37620656 0.34602073
17  0.3126251 0.37708945 0.31028546
18  0.3293898 0.23309322 0.43751702
19  0.3293898 0.23309322 0.43751702
20  0.6324598 0.20043415 0.16710605
21  0.1998583 0.21215265 0.58798910
22  0.2888779 0.22953567 0.48158639
23  0.3306609 0.37639623 0.29294288
24  0.2777727 0.37620656 0.34602073
25  0.1726885 0.35083838 0.47647308
26  0.3966333 0.23772084 0.36564585
27  0.3676935 0.37276244 0.25954407
28  0.2888779 0.22953567 0.48158639
29  0.2292007 0.36934060 0.40145871
30  0.3865787 0.36985032 0.24357101
31  0.2888779 0.22953567 0.48158639
32  0.1996911 0.36131499 0.43899395
33  0.2141410 0.36565296 0.42020603
34  0.3126251 0.37708945 0.31028546
35  0.2331292 0.22039757 0.54647324
36  0.1998583 0.21215265 0.58798910
37  0.1202017 0.18062830 0.69916997
38  0.7921407 0.14065656 0.06720272
39  0.2292007 0.36934060 0.40145871
40  0.3504532 0.23404073 0.41550609
41  0.1001231 0.16893737 0.73093949
42  0.4852936 0.23070135 0.28400507
43  0.4823541 0.34543275 0.17221315
44  0.4408612 0.23532266 0.32381609
45  0.2777727 0.37620656 0.34602073
46  0.4632141 0.35150976 0.18527617
47  0.3293898 0.23309322 0.43751702
48  0.4632141 0.35150976 0.18527617
49  0.2509706 0.22391068 0.52511877
50  0.3937910 0.23421301 0.37199598
51  0.2331292 0.22039757 0.54647324
52  0.2331292 0.22039757 0.54647324
53  0.2777727 0.37620656 0.34602073
54  0.5202215 0.33179483 0.14798364
55  0.4604652 0.23018005 0.30935477
56  0.3676935 0.37276244 0.25954407
57  0.4630986 0.23327985 0.30362151
58  0.7657822 0.15267894 0.08153887
59  0.6102774 0.29135200 0.09837060
60  0.2917502 0.23360371 0.47464612
61  0.5049270 0.22479322 0.27027983
62  0.2160825 0.21646512 0.56745234
63  0.6876322 0.18315578 0.12921205
64  0.5698425 0.21322354 0.21693394
65  0.3937910 0.23421301 0.37199598
66  0.3293898 0.23309322 0.43751702
67  0.5202215 0.33179483 0.14798364
68  0.3937910 0.23421301 0.37199598
69  0.4604652 0.23018005 0.30935477
70  0.4827571 0.22774111 0.28950178
71  0.7210140 0.17103773 0.10794824
72  0.5698425 0.21322354 0.21693394
73  0.4630986 0.23327985 0.30362151
74  0.4247955 0.36195269 0.21325179
75  0.5698425 0.21322354 0.21693394
76  0.4632141 0.35150976 0.18527617
77  0.4604652 0.23018005 0.30935477
78  0.4604652 0.23018005 0.30935477
79  0.2888779 0.22953567 0.48158639
80  0.3293898 0.23309322 0.43751702
81  0.3676935 0.37276244 0.25954407
82  0.5049270 0.22479322 0.27027983
83  0.6876322 0.18315578 0.12921205
84  0.2777727 0.37620656 0.34602073
85  0.6324598 0.20043415 0.16710605
86  0.3126251 0.37708945 0.31028546
87  0.5049270 0.22479322 0.27027983
88  0.1998583 0.21215265 0.58798910
89  0.6110367 0.20362512 0.18533822
90  0.3088400 0.23158545 0.45957451
91  0.6876322 0.18315578 0.12921205
92  0.7210140 0.17103773 0.10794824
93  0.5291960 0.22405052 0.24675343
94  0.4158872 0.23343321 0.35067961
95  0.6685375 0.18724728 0.14421521
96  0.6110367 0.20362512 0.18533822
97  0.4604652 0.23018005 0.30935477
98  0.4604652 0.23018005 0.30935477
99  0.3293898 0.23309322 0.43751702
100 0.2331292 0.22039757 0.54647324
101 0.4604652 0.23018005 0.30935477
102 0.4604652 0.23018005 0.30935477
103 0.5268859 0.22136713 0.25174694
104 0.2331292 0.22039757 0.54647324
105 0.3937910 0.23421301 0.37199598
106 0.5572058 0.31650507 0.12628915
107 0.4632141 0.35150976 0.18527617
108 0.5049270 0.22479322 0.27027983
109 0.6110367 0.20362512 0.18533822
110 0.5268859 0.22136713 0.25174694
111 0.6102774 0.29135200 0.09837060
112 0.5049270 0.22479322 0.27027983
113 0.5049270 0.22479322 0.27027983
114 0.5049270 0.22479322 0.27027983
115 0.6110367 0.20362512 0.18533822
116 0.5698425 0.21322354 0.21693394
117 0.8158376 0.12901647 0.05514591
118 0.6876322 0.18315578 0.12921205
119 0.6110367 0.20362512 0.18533822
120 0.6685375 0.18724728 0.14421521
121 0.5752548 0.30836653 0.11637863
122 0.6110367 0.20362512 0.18533822
123 0.7200349 0.16949969 0.11046543
124 0.8158376 0.12901647 0.05514591
125 0.6110367 0.20362512 0.18533822
126 0.7921407 0.14065656 0.06720272
127 0.6110367 0.20362512 0.18533822
128 0.6110367 0.20362512 0.18533822
129 0.7200349 0.16949969 0.11046543
130 0.7657822 0.15267894 0.08153887
131 0.6110367 0.20362512 0.18533822
132 0.6324598 0.20043415 0.16710605
133 0.3676935 0.37276244 0.25954407
134 0.7921407 0.14065656 0.06720272
135 0.6685375 0.18724728 0.14421521
136 0.7921407 0.14065656 0.06720272
137 0.5049270 0.22479322 0.27027983
138 0.8370332 0.11788753 0.04507931
139 0.2610484 0.37464158 0.36431000
140 0.7210140 0.17103773 0.10794824
141 0.6876322 0.18315578 0.12921205
142 0.5202215 0.33179483 0.14798364
143 0.5698425 0.21322354 0.21693394
144 0.5698425 0.21322354 0.21693394
145 0.6500011 0.19291318 0.15708576
146 0.6685375 0.18724728 0.14421521
147 0.6685375 0.18724728 0.14421521
148 0.6596792 0.26469707 0.07562378
149 0.5698425 0.21322354 0.21693394
150 0.7921407 0.14065656 0.06720272
151 0.6110367 0.20362512 0.18533822
152 0.8267369 0.12338166 0.04988149
153 0.7200349 0.16949969 0.11046543
154 0.6685375 0.18724728 0.14421521
155 0.6102774 0.29135200 0.09837060
156 0.6685375 0.18724728 0.14421521
157 0.7210140 0.17103773 0.10794824
158 0.8267369 0.12338166 0.04988149
159 0.6596792 0.26469707 0.07562378
160 0.8267369 0.12338166 0.04988149
161 0.8726772 0.09748693 0.02983585
162 0.8559136 0.10735910 0.03672735
163 0.5752548 0.30836653 0.11637863
164 0.7921407 0.14065656 0.06720272
165 0.6110367 0.20362512 0.18533822
166 0.6110367 0.20362512 0.18533822
167 0.8559136 0.10735910 0.03672735
168 0.8267369 0.12338166 0.04988149
169 0.8559136 0.10735910 0.03672735
170 0.7921407 0.14065656 0.06720272
171 0.5572058 0.31650507 0.12628915
172 0.8158376 0.12901647 0.05514591
173 0.6596792 0.26469707 0.07562378
174 0.8726772 0.09748693 0.02983585
175 0.8559136 0.10735910 0.03672735
176 0.6596792 0.26469707 0.07562378
177 0.7508140 0.15740972 0.09177625
178 0.6596792 0.26469707 0.07562378
179 0.6102774 0.29135200 0.09837060
180 0.6876322 0.18315578 0.12921205
181 0.8370332 0.11788753 0.04507931
182 0.6110367 0.20362512 0.18533822
183 0.8559136 0.10735910 0.03672735
184 0.6110367 0.20362512 0.18533822
185 0.8726772 0.09748693 0.02983585
186 0.8726772 0.09748693 0.02983585
187 0.8043127 0.13477968 0.06090766
188 0.8726772 0.09748693 0.02983585
189 0.8267369 0.12338166 0.04988149
190 0.5049270 0.22479322 0.27027983
191 0.8559136 0.10735910 0.03672735
192 0.8267369 0.12338166 0.04988149
193 0.6110367 0.20362512 0.18533822
194 0.8043127 0.13477968 0.06090766
195 0.8370332 0.11788753 0.04507931
196 0.8559136 0.10735910 0.03672735
197 0.6864017 0.18143036 0.13216795
198 0.7508140 0.15740972 0.09177625
199 0.7200349 0.16949969 0.11046543
200 0.6685375 0.18724728 0.14421521</code></pre>
</div>
</div>
<p>A continuación, si queremos examinar los cambios en la probabilidad predicha asociados con una de nuestras dos variables, podemos crear pequeños conjuntos de datos variando una variable mientras mantenemos la otra constante.</p>
<p>Primero haremos esto manteniendo write su media y examinando las probabilidades predichas para cada nivel de ses.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>dses <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">ses =</span> <span class="fu">c</span>(<span class="st">"low"</span>, <span class="st">"middle"</span>, <span class="st">"high"</span>), <span class="at">write =</span> <span class="fu">mean</span>(ml<span class="sc">$</span>write))</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>dses</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["ses"],"name":[1],"type":["chr"],"align":["left"]},{"label":["write"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"low","2":"52.775"},{"1":"middle","2":"52.775"},{"1":"high","2":"52.775"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(test, <span class="at">newdata =</span> dses, <span class="st">"probs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   academic   general  vocation
1 0.4396845 0.3581917 0.2021238
2 0.4777488 0.2283353 0.2939159
3 0.7009007 0.1784939 0.1206054</code></pre>
</div>
</div>
<p>Otra forma de entender el modelo es utilizando las probabilidades predichas para observar las probabilidades promediadas predichas para diferentes valores de la variable predictora continua write dentro de cada nivel de ses.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>dwrite <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">ses =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"low"</span>, <span class="st">"middle"</span>, <span class="st">"high"</span>),</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>                               <span class="at">each =</span> <span class="dv">41</span>), <span class="at">write =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="dv">30</span><span class="sc">:</span><span class="dv">70</span>), <span class="dv">3</span>))</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="do">## almacene las probabilidades predichas para cada valor de ses</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>pp.write <span class="ot">&lt;-</span> <span class="fu">cbind</span>(dwrite, <span class="fu">predict</span>(test, <span class="at">newdata =</span> dwrite, <span class="at">type =</span> <span class="st">"probs"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>))</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a><span class="do">## calcular las probabilidades medias dentro de cada nivel de ses </span></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a><span class="fu">by</span>(pp.write[, <span class="dv">3</span><span class="sc">:</span><span class="dv">5</span>], pp.write<span class="sc">$</span>ses, colMeans)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>pp.write$ses: high
 academic   general  vocation 
0.6164315 0.1808037 0.2027648 
------------------------------------------------------------ 
pp.write$ses: low
 academic   general  vocation 
0.3972977 0.3278174 0.2748849 
------------------------------------------------------------ 
pp.write$ses: middle
 academic   general  vocation 
0.4256198 0.2010864 0.3732938 </code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Grafico probabilidades predichas</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Pasar la base a formato long para utilizar ggplot</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>lpp <span class="ot">&lt;-</span> <span class="fu">melt</span>(pp.write, <span class="at">id.vars =</span> <span class="fu">c</span>(<span class="st">"ses"</span>, <span class="st">"write"</span>), <span class="at">value.name =</span> <span class="st">"probability"</span>)</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(lpp, <span class="fu">aes</span>(<span class="at">x =</span> write, <span class="at">y =</span> probability, <span class="at">colour =</span> ses)) <span class="sc">+</span></span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(variable <span class="sc">~</span> ., <span class="at">scales =</span> <span class="st">"free"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="clase05_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(marginaleffects)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="fu">avg_slopes</span>(test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["term"],"name":[1],"type":["chr"],"align":["left"]},{"label":["group"],"name":[2],"type":["chr"],"align":["left"]},{"label":["contrast"],"name":[3],"type":["chr"],"align":["left"]},{"label":["estimate"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["std.error"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["statistic"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["p.value"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["s.value"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["conf.low"],"name":[9],"type":["dbl"],"align":["right"]},{"label":["conf.high"],"name":[10],"type":["dbl"],"align":["right"]}],"data":[{"1":"ses","2":"academic","3":"high - low","4":"0.231807733","5":"0.093666513","6":"2.4748197","7":"1.333034e-02","8":"6.2291421","9":"0.04822474","10":"0.415390725"},{"1":"ses","2":"academic","3":"middle - low","4":"0.035763932","5":"0.084057086","6":"0.4254719","7":"6.704927e-01","8":"0.5767065","9":"-0.12898493","10":"0.200512793"},{"1":"write","2":"academic","3":"dY/dX","4":"0.017141067","5":"0.002876642","6":"5.9587071","7":"2.542413e-09","8":"28.5511544","9":"0.01150295","10":"0.022779182"},{"1":"ses","2":"general","3":"high - low","4":"-0.160056208","5":"0.086862156","6":"-1.8426460","7":"6.538071e-02","8":"3.9349912","9":"-0.33030291","10":"0.010190489"},{"1":"ses","2":"general","3":"middle - low","4":"-0.124467796","5":"0.079925575","6":"-1.5572962","7":"1.194002e-01","8":"3.0661231","9":"-0.28111904","10":"0.032183453"},{"1":"write","2":"general","3":"dY/dX","4":"-0.002829677","5":"0.002824492","6":"-1.0018355","7":"3.164230e-01","8":"1.6600734","9":"-0.00836558","10":"0.002706226"},{"1":"ses","2":"vocation","3":"high - low","4":"-0.071751525","5":"0.074322063","6":"-0.9654135","7":"3.343377e-01","8":"1.5806219","9":"-0.21742009","10":"0.073917042"},{"1":"ses","2":"vocation","3":"middle - low","4":"0.088703864","5":"0.069819230","6":"1.2704790","7":"2.039141e-01","8":"2.2939668","9":"-0.04813931","10":"0.225547040"},{"1":"write","2":"vocation","3":"dY/dX","4":"-0.014311391","5":"0.002511473","6":"-5.6984041","7":"1.209341e-08","8":"26.3012033","9":"-0.01923379","10":"-0.009388993"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>En este bloque de código, estoy calculando los efectos promedio marginales en un modelo multinomial para entender cómo las variables independientes ses (nivel socioeconómico) y write (puntuación de escritura) influyen en la probabilidad de estar en diferentes grupos de la variable dependiente (academic, general, vocation).</p>
<p>Estos resultados permiten interpretar el cambio promedio en la probabilidad de estar en cada grupo, condicionado a cambios en las variables independientes, proporcionando una comprensión detallada de los efectos específicos.</p>
<p><strong>Resultados del modelo multinomial</strong></p>
<blockquote class="blockquote">
<p>Group: academic</p>
</blockquote>
<ul>
<li><p>ses: high - low (Estimate: 0.23181, Std. Error: 0.09367, z-value: 2.475, Pr(&gt;|z|): 0.0133)</p></li>
<li><p>Un nivel socioeconómico alto comparado con un nivel bajo aumenta la probabilidad de estar en el grupo ‘academic’ en 0.23181 unidades en la escala logit. Este efecto es estadísticamente significativo (p-valor = 0.0133).</p></li>
<li><p>ses: middle - low (Estimate: 0.03576, Std. Error: 0.08406, z-value: 0.425, Pr(&gt;|z|): 0.6705)</p></li>
<li><p>Un nivel socioeconómico medio comparado con un nivel bajo tiene un efecto positivo muy pequeño y no significativo en la probabilidad de estar en el grupo ‘academic’.</p></li>
<li><p>write: dY/dX (Estimate: 0.01714, Std. Error: 0.00288, z-value: 5.959, Pr(&gt;|z|): &lt;0.001)</p></li>
<li><p>Un incremento en una unidad en la puntuación de escritura aumenta la probabilidad de estar en el grupo ‘academic’ en 0.01714. Este efecto es altamente significativo (p-valor &lt; 0.001).</p></li>
</ul>
<blockquote class="blockquote">
<p>Group: general</p>
</blockquote>
<ul>
<li><p>ses: high - low (Estimate: -0.16006, Std. Error: 0.08686, z-value: -1.843, Pr(&gt;|z|): 0.0654)</p></li>
<li><p>Un nivel socioeconómico alto comparado con un nivel bajo disminuye la probabilidad de estar en el grupo ‘general’ en 0.16006 unidades en la escala logit. Este efecto es marginalmente significativo (p-valor = 0.0654).</p></li>
<li><p>ses: middle - low (Estimate: -0.12447, Std. Error: 0.07993, z-value: -1.557, Pr(&gt;|z|): 0.1194)</p></li>
<li><p>Un nivel socioeconómico medio comparado con un nivel bajo tiene un efecto negativo y no significativo en la probabilidad de estar en el grupo ‘general’.</p></li>
<li><p>write: dY/dX (Estimate: -0.00283, Std. Error: 0.00282, z-value: -1.002, Pr(&gt;|z|): 0.3164)</p></li>
<li><p>Un incremento en una unidad en la puntuación de escritura disminuye la probabilidad de estar en el grupo ‘general’ en 0.00283. Este efecto no es significativo (p-valor = 0.3164).</p></li>
</ul>
<blockquote class="blockquote">
<p>Group: vocation</p>
</blockquote>
<ul>
<li><p>ses: high - low (Estimate: -0.07175, Std. Error: 0.07432, z-value: -0.965, Pr(&gt;|z|): 0.3343)</p></li>
<li><p>Un nivel socioeconómico alto comparado con un nivel bajo disminuye la probabilidad de estar en el grupo ‘vocation’ en 0.07175 unidades en la escala logit. Este efecto no es significativo (p-valor = 0.3343).</p></li>
<li><p>ses: middle - low (Estimate: 0.08870, Std. Error: 0.06982, z-value: 1.270, Pr(&gt;|z|): 0.2039)</p></li>
<li><p>Un nivel socioeconómico medio comparado con un nivel bajo aumenta la probabilidad de estar en el grupo ‘vocation’ en 0.08870 unidades en la escala logit. Este efecto no es significativo (p-valor = 0.2039).</p></li>
<li><p>write: dY/dX (Estimate: -0.01431, Std. Error: 0.00251, z-value: -5.698, Pr(&gt;|z|): &lt;0.001)</p></li>
<li><p>Un incremento en una unidad en la puntuación de escritura disminuye la probabilidad de estar en el grupo ‘vocation’ en 0.01431. Este efecto es altamente significativo (p-valor &lt; 0.001).</p></li>
</ul>
</section>
</section>
<section id="taller" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Taller</h1>
<section id="objetivo" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="objetivo"><span class="header-section-number">6.1</span> Objetivo</h2>
<p>Modelar una elección con ≥3 categorías nominales y responder preguntas de política/gestión con probabilidades predichas, efectos marginales, etc.</p>
</section>
<section id="fuentes-sugeridas" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="fuentes-sugeridas"><span class="header-section-number">6.2</span> Fuentes sugeridas</h2>
<p>World Bank Data (DataBank), OECD Data, Our World in Data, UN Data, FAOSTAT, IMF Data.</p>
<blockquote class="blockquote">
<p>Elijan un dataset con ≥ 300 observaciones (país-año, hogares, empresas, etc) y variables claras. Importante que la frecuencia en las clases sea balanceada.</p>
</blockquote>
</section>
<section id="ejemplos-de-preguntas" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="ejemplos-de-preguntas"><span class="header-section-number">6.3</span> Ejemplos de preguntas</h2>
<p><strong>Transporte</strong></p>
<blockquote class="blockquote">
<p>¿Qué factores explican elegir bus/metro/bici/auto? Y: modo. X: tiempo, costo, clima, ingresos. Contrafactual: −10% en tiempo del metro → ¿nuevos shares?</p>
</blockquote>
<blockquote class="blockquote">
<p>¿Cómo cambian las elecciones Uber/taxi/bus según hora del día? Y: servicio. X: hora pico, tarifa dinámica, lluvia. Contrafactual: +15% tarifa Uber.</p>
</blockquote>
<p><strong>Educación</strong></p>
<blockquote class="blockquote">
<p>¿Qué perfila la elección de programa académico/general/vocacional? Y: programa. X: puntaje, SES, género, escuela previa. Contrafactual: +10 puntos en “write”.</p>
</blockquote>
<blockquote class="blockquote">
<p>¿Qué determina escoger universidad pública/privada/externa? Y: tipo de institución. X: ingreso hogar, becas, distancia. Contrafactual: beca del 50% en privada.</p>
</blockquote>
<p><strong>Salud</strong></p>
<blockquote class="blockquote">
<p>¿Qué lleva a elegir EPS A/EPS B/privado? Y: proveedor. X: prima, tiempo de espera, edad, crónicos. Contrafactual: reducir espera en EPS B a 20 min.</p>
</blockquote>
<blockquote class="blockquote">
<p>En urgencias, ¿por qué eligen clínica X/clínica Y/hospital? Y: centro. X: distancia, saturación, seguro. Contrafactual: abrir nueva sede de la clínica X más cerca.</p>
</blockquote>
<p><strong>Finanzas</strong></p>
<blockquote class="blockquote">
<p>¿Qué define elegir tarjeta débito/crédito/fintech para pagar? Y: método. X: ingresos, comisiones, cashback, edad. Contrafactual: +2% cashback en fintech.</p>
</blockquote>
<blockquote class="blockquote">
<p>¿Qué influye en tipo de cuenta (básica/premium/pyme)? Y: producto. X: tarifas, uso mensual, score. Contrafactual: eximir cuota de manejo en “premium”.</p>
</blockquote>
<p><strong>Consumo/Marketing</strong></p>
<blockquote class="blockquote">
<p>¿Qué explica elegir marca A/B/C de café? Y: marca. X: precio, sello orgánico, origen, reseñas. Contrafactual: certificación orgánica para B.</p>
</blockquote>
<blockquote class="blockquote">
<p>Delivery: Rappi/UberEats/DidiFood Y: plataforma. X: costo envío, tiempo, cupones, rating. Contrafactual: cupón 30% en Rappi.</p>
</blockquote>
<p><strong>Energía/Ambiente</strong></p>
<blockquote class="blockquote">
<p>¿Qué determina el combustible de cocina gas/electricidad/biomasa? Y: combustible. X: ingreso, subsidio, zona, precio relativo. Contrafactual: bajar precio de electricidad 15%.</p>
</blockquote>
</section>
<section id="pasos-mínimos" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="pasos-mínimos"><span class="header-section-number">6.4</span> Pasos (mínimos)</h2>
<ol type="1">
<li><p>Pregunta y alternativas Define la decisión a modelar y las categorías nominales (≥3). Explica por qué no es binario ni ordinal. Fija la categoría base.</p></li>
<li><p>Datos y limpieza Fuente, tamaño (≥300 obs. sugerido), definiciones, recodificaciones a factor, outliers/NA, y una tabla de frecuencias por categoría.</p></li>
<li><p>Modelo (MNL) Especifica y ~ x1 + x2 + … (incluye 1 interacción simple si tiene sentido). Explica la plausibilidad del IIA (antes de estimar): ¿hay “clones”?</p></li>
<li><p>Estimación y lectura Ajusta con nnet::multinom. Reporta coeficientes, odds ratios (OR) y p-valores (Wald). Interpreta por categoría vs.&nbsp;baseline.</p></li>
<li><p>Validación/diagnóstico Pseudo-R², log-likelihood, tasa de acierto (matriz de confusión).</p></li>
<li><p>Predicciones Construye perfiles y reporta probabilidades predichas P(y=j | x); grafica P vs.&nbsp;un predictor clave con facetas por categoría.</p></li>
</ol>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb57" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Regresión Cuantil"</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Orlando Joaqui-Barandica"</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> last-modified</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a><span class="co">    number-sections: true</span></span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: show</span></span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a><span class="co">    df-print: paged</span></span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a><span class="co">    theme: cosmo</span></span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb57-14"><a href="#cb57-14" aria-hidden="true" tabindex="-1"></a><span class="co">  echo: true</span></span>
<span id="cb57-15"><a href="#cb57-15" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: false</span></span>
<span id="cb57-16"><a href="#cb57-16" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb57-17"><a href="#cb57-17" aria-hidden="true" tabindex="-1"></a><span class="an">freeze:</span><span class="co"> auto</span></span>
<span id="cb57-18"><a href="#cb57-18" aria-hidden="true" tabindex="-1"></a><span class="an">editor:</span><span class="co"> visual</span></span>
<span id="cb57-19"><a href="#cb57-19" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb57-20"><a href="#cb57-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-21"><a href="#cb57-21" aria-hidden="true" tabindex="-1"></a><span class="fu"># Materiales</span></span>
<span id="cb57-22"><a href="#cb57-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-23"><a href="#cb57-23" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>R ≥ 4.1 y paquetes: <span class="in">`quantreg`</span>, <span class="in">`ggplot2`</span>, <span class="in">`dplyr`</span>, <span class="in">`AER`</span>, <span class="in">`broom`</span>, <span class="in">`purrr`</span>, <span class="in">`tidyr`</span>, <span class="in">`scales`</span>.</span>
<span id="cb57-24"><a href="#cb57-24" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Dataset de ejemplo: <span class="in">`AER::CPS1985`</span> (salarios en EE. UU. 1985).</span>
<span id="cb57-25"><a href="#cb57-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-28"><a href="#cb57-28" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-29"><a href="#cb57-29" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb57-30"><a href="#cb57-30" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb57-31"><a href="#cb57-31" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb57-32"><a href="#cb57-32" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb57-33"><a href="#cb57-33" aria-hidden="true" tabindex="-1"></a>required <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"quantreg"</span>,<span class="st">"ggplot2"</span>,<span class="st">"dplyr"</span>,<span class="st">"AER"</span>,<span class="st">"broom"</span>,<span class="st">"purrr"</span>,<span class="st">"tidyr"</span>,<span class="st">"scales"</span>)</span>
<span id="cb57-34"><a href="#cb57-34" aria-hidden="true" tabindex="-1"></a>missing <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(required, <span class="fu">rownames</span>(<span class="fu">installed.packages</span>()))</span>
<span id="cb57-35"><a href="#cb57-35" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="fu">length</span>(missing)) <span class="fu">install.packages</span>(missing)</span>
<span id="cb57-36"><a href="#cb57-36" aria-hidden="true" tabindex="-1"></a><span class="fu">invisible</span>(<span class="fu">lapply</span>(required, library, <span class="at">character.only =</span> <span class="cn">TRUE</span>))</span>
<span id="cb57-37"><a href="#cb57-37" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb57-38"><a href="#cb57-38" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb57-39"><a href="#cb57-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-40"><a href="#cb57-40" aria-hidden="true" tabindex="-1"></a><span class="fu"># Resumen de la sesión</span></span>
<span id="cb57-41"><a href="#cb57-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-42"><a href="#cb57-42" aria-hidden="true" tabindex="-1"></a>En esta sesión introducimos **modelos de elección discreta** para variables dependientes cualitativas. Empezamos con casos binarios y el **modelo Logit** (formulación, interpretación y validación) y avanzamos a elecciones con **m\&gt;2** alternativas mediante **Logit Multinomial**. Cerraremos con criterios para decidir entre **binario, multinomial u ordinal** y simulaciones reproducibles (código oculto).</span>
<span id="cb57-43"><a href="#cb57-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-44"><a href="#cb57-44" aria-hidden="true" tabindex="-1"></a><span class="fu"># Objetivos de aprendizaje</span></span>
<span id="cb57-45"><a href="#cb57-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-46"><a href="#cb57-46" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Distinguir entre variables **binarias, ordinales y nominales** y seleccionar el modelo adecuado.</span>
<span id="cb57-47"><a href="#cb57-47" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Formular e interpretar un **Logit** (odds, OR, efectos marginales y ajuste).</span>
<span id="cb57-48"><a href="#cb57-48" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Entender la teoría de **utilidad aleatoria** y la especificación del **Logit Multinomial**.</span>
<span id="cb57-49"><a href="#cb57-49" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Reconocer cuándo usar **modelos ordinales** (líneas paralelas) vs **multinomiales**.</span>
<span id="cb57-50"><a href="#cb57-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-51"><a href="#cb57-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-52"><a href="#cb57-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-53"><a href="#cb57-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-54"><a href="#cb57-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-55"><a href="#cb57-55" aria-hidden="true" tabindex="-1"></a><span class="fu"># Marco conceptual</span></span>
<span id="cb57-56"><a href="#cb57-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-57"><a href="#cb57-57" aria-hidden="true" tabindex="-1"></a>Los **modelos de elección discreta** estudian la probabilidad de que un individuo elija una opción dentro de un conjunto finito. Ejemplos: </span>
<span id="cb57-58"><a href="#cb57-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-59"><a href="#cb57-59" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>(i) **Adopción de un crédito** (sí/no)</span>
<span id="cb57-60"><a href="#cb57-60" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>(ii) **Compra online** (sí/no)</span>
<span id="cb57-61"><a href="#cb57-61" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>(iii) **Modo de transporte** (bus/auto/bici)</span>
<span id="cb57-62"><a href="#cb57-62" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>(iv) **Elección de marca** (m&gt;2, nominal)</span>
<span id="cb57-63"><a href="#cb57-63" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>(v) **Satisfacción** en escalas Likert (ordinal).</span>
<span id="cb57-64"><a href="#cb57-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-65"><a href="#cb57-65" aria-hidden="true" tabindex="-1"></a><span class="fu">## Elección binaria y modelo Logit</span></span>
<span id="cb57-66"><a href="#cb57-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-67"><a href="#cb57-67" aria-hidden="true" tabindex="-1"></a>Sea $(Y_i \in {0,1})$. El **Logit** modela $(p_i=Pr(Y_i=1\mid X_i))$ con </span>
<span id="cb57-68"><a href="#cb57-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-69"><a href="#cb57-69" aria-hidden="true" tabindex="-1"></a>$$ p_i=\frac{1}{1+e^{-X_i'\beta}} \quad \Rightarrow \quad \log\frac{p_i}{1-p_i}=X_i'\beta. $$</span>
<span id="cb57-70"><a href="#cb57-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-71"><a href="#cb57-71" aria-hidden="true" tabindex="-1"></a>Se estima por máxima verosimilitud; los coeficientes se interpretan como odds ratios $(\exp(\beta_j))$; los efectos en probabilidad mediante **efectos marginales**.</span>
<span id="cb57-72"><a href="#cb57-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-73"><a href="#cb57-73" aria-hidden="true" tabindex="-1"></a>::: callout-important</span>
<span id="cb57-74"><a href="#cb57-74" aria-hidden="true" tabindex="-1"></a>**Cuándo usar Logit (binario):** cuando la respuesta tiene 2 categorías excluyentes y nos interesa modelar **probabilidades** acotadas en $(0,1)$ con elasticidad no lineal. Evita el **MLP** por predicciones fuera de $(0,1)$, heterocedasticidad y linealidad estricta.</span>
<span id="cb57-75"><a href="#cb57-75" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb57-76"><a href="#cb57-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-77"><a href="#cb57-77" aria-hidden="true" tabindex="-1"></a><span class="fu">## De binario a multinomial</span></span>
<span id="cb57-78"><a href="#cb57-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-79"><a href="#cb57-79" aria-hidden="true" tabindex="-1"></a>Cuando $(m&gt;2)$ sin orden, partimos de **utilidad aleatoria**: </span>
<span id="cb57-80"><a href="#cb57-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-81"><a href="#cb57-81" aria-hidden="true" tabindex="-1"></a>El individuo (i) elige la alternativa (j) con mayor utilidad </span>
<span id="cb57-82"><a href="#cb57-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-83"><a href="#cb57-83" aria-hidden="true" tabindex="-1"></a>$$(U_{ij}=X_i'\beta_j+\varepsilon_{ij})$$. </span>
<span id="cb57-84"><a href="#cb57-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-85"><a href="#cb57-85" aria-hidden="true" tabindex="-1"></a>Con errores i.i.d. se deriva el **Logit Multinomial** (base category logit): </span>
<span id="cb57-86"><a href="#cb57-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-87"><a href="#cb57-87" aria-hidden="true" tabindex="-1"></a>$$Pr(Y_i=j\mid X_i)=\frac{\exp(X_i'\beta_j)}{\sum_{h=0}^{m-1}\exp(X_i'\beta_h)},$$</span>
<span id="cb57-88"><a href="#cb57-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-89"><a href="#cb57-89" aria-hidden="true" tabindex="-1"></a>Relación con múltiples logits binarios y eficiencia de estimar **simultáneamente** (vs. pares por separado). Considere el supuesto **IIA** (independencia de alternativas irrelevantes) y sus implicaciones empíricas.</span>
<span id="cb57-90"><a href="#cb57-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-91"><a href="#cb57-91" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb57-92"><a href="#cb57-92" aria-hidden="true" tabindex="-1"></a>**¿Multinomial u ordinal?** Si las categorías tienen **orden** (p. ej., *baja, media, alta*), prefiera **logit/probit ordinal** (líneas paralelas). Usar un modelo nominal sobre datos ordinales pierde eficiencia; usar un ordinal sobre datos nominales introduce **sesgo**.</span>
<span id="cb57-93"><a href="#cb57-93" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb57-94"><a href="#cb57-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-95"><a href="#cb57-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-96"><a href="#cb57-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-97"><a href="#cb57-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-98"><a href="#cb57-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-99"><a href="#cb57-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-100"><a href="#cb57-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-101"><a href="#cb57-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-102"><a href="#cb57-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-103"><a href="#cb57-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-104"><a href="#cb57-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-105"><a href="#cb57-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-106"><a href="#cb57-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-107"><a href="#cb57-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-108"><a href="#cb57-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-109"><a href="#cb57-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-110"><a href="#cb57-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-111"><a href="#cb57-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-112"><a href="#cb57-112" aria-hidden="true" tabindex="-1"></a><span class="fu"># Codigo Modelo Logit - Probit</span></span>
<span id="cb57-113"><a href="#cb57-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-114"><a href="#cb57-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-115"><a href="#cb57-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-116"><a href="#cb57-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-117"><a href="#cb57-117" aria-hidden="true" tabindex="-1"></a>Un investigador está interesado en cómo las variables, como el GRE (puntaje del examen de Graduados), el GPA (promedio de calificaciones) y el prestigio de la institución de pregrado, tienen efecto en la admisión a la escuela de postgrado.</span>
<span id="cb57-118"><a href="#cb57-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-119"><a href="#cb57-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-120"><a href="#cb57-120" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; La variable de respuesta, admitir / no admitir, es una variable binaria.</span></span>
<span id="cb57-121"><a href="#cb57-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-122"><a href="#cb57-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-123"><a href="#cb57-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-126"><a href="#cb57-126" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-127"><a href="#cb57-127" aria-hidden="true" tabindex="-1"></a><span class="do">######################################</span></span>
<span id="cb57-128"><a href="#cb57-128" aria-hidden="true" tabindex="-1"></a><span class="co">#Modelo Logit - Probit</span></span>
<span id="cb57-129"><a href="#cb57-129" aria-hidden="true" tabindex="-1"></a><span class="do">######################################</span></span>
<span id="cb57-130"><a href="#cb57-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-131"><a href="#cb57-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-132"><a href="#cb57-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-133"><a href="#cb57-133" aria-hidden="true" tabindex="-1"></a>mydata <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Datos/binary.csv"</span>)</span>
<span id="cb57-134"><a href="#cb57-134" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mydata)</span>
<span id="cb57-135"><a href="#cb57-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-136"><a href="#cb57-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-137"><a href="#cb57-137" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mydata)</span>
<span id="cb57-138"><a href="#cb57-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-139"><a href="#cb57-139" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(mydata, sd)</span>
<span id="cb57-140"><a href="#cb57-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-141"><a href="#cb57-141" aria-hidden="true" tabindex="-1"></a><span class="fu">xtabs</span>(<span class="sc">~</span>admit <span class="sc">+</span> rank, <span class="at">data =</span> mydata)</span>
<span id="cb57-142"><a href="#cb57-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-143"><a href="#cb57-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-144"><a href="#cb57-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-145"><a href="#cb57-145" aria-hidden="true" tabindex="-1"></a><span class="co"># MODELO LOGIT </span></span>
<span id="cb57-146"><a href="#cb57-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-147"><a href="#cb57-147" aria-hidden="true" tabindex="-1"></a>mydata<span class="sc">$</span>rank <span class="ot">&lt;-</span> <span class="fu">factor</span>(mydata<span class="sc">$</span>rank)</span>
<span id="cb57-148"><a href="#cb57-148" aria-hidden="true" tabindex="-1"></a>mylogit <span class="ot">&lt;-</span> <span class="fu">glm</span>(admit <span class="sc">~</span> gre <span class="sc">+</span> gpa <span class="sc">+</span> rank, <span class="at">data =</span> mydata, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb57-149"><a href="#cb57-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-150"><a href="#cb57-150" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mylogit)</span>
<span id="cb57-151"><a href="#cb57-151" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb57-152"><a href="#cb57-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-153"><a href="#cb57-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-154"><a href="#cb57-154" aria-hidden="true" tabindex="-1"></a>Tanto gre como gpa son estadísticamente significativos, al igual que los tres términos para rango. Los coeficientes de regresión logística dan el cambio en las probabilidades del logaritmo del resultado para un aumento de una unidad en la variable predictora.</span>
<span id="cb57-155"><a href="#cb57-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-156"><a href="#cb57-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-157"><a href="#cb57-157" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Por cada cambio de unidades en gre, las probabilidades log de admisión (versus no admisión) aumentan en 0.002. </span>
<span id="cb57-158"><a href="#cb57-158" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Para un aumento de una unidad en gpa, las probabilidades de registro de admisión a la escuela de posgrado aumenta en 0,804.</span>
<span id="cb57-159"><a href="#cb57-159" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Las variables indicadoras de rango tienen una interpretación ligeramente diferente. </span>
<span id="cb57-160"><a href="#cb57-160" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Por ejemplo, haber asistido a una institución de pregrado con un rango de 2, frente a una institución con un rango de 1,cambia las probabilidades de registro de admisión en -0.675.</span>
<span id="cb57-161"><a href="#cb57-161" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Debajo de la tabla de coeficientes se encuentran los índices de ajuste, incluidos los residuales nulos y de desviación y el AIC. </span>
<span id="cb57-162"><a href="#cb57-162" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Más adelante mostramos un ejemplo de cómo puede usar estos valores para ayudar a evaluar el ajuste del modelo.</span>
<span id="cb57-163"><a href="#cb57-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-164"><a href="#cb57-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-165"><a href="#cb57-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-166"><a href="#cb57-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-169"><a href="#cb57-169" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-170"><a href="#cb57-170" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mylogit) <span class="co"># Usando Max. Verosimilitud</span></span>
<span id="cb57-171"><a href="#cb57-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-172"><a href="#cb57-172" aria-hidden="true" tabindex="-1"></a><span class="fu">confint.default</span>(mylogit) <span class="co">#Usando errores estándar</span></span>
<span id="cb57-173"><a href="#cb57-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-174"><a href="#cb57-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-175"><a href="#cb57-175" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(mylogit)) <span class="co"># Odds ratios</span></span>
<span id="cb57-176"><a href="#cb57-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-177"><a href="#cb57-177" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="at">OR =</span> <span class="fu">coef</span>(mylogit), <span class="fu">confint</span>(mylogit))) <span class="co"># Odds ratios - Int. Conf.</span></span>
<span id="cb57-178"><a href="#cb57-178" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb57-179"><a href="#cb57-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-180"><a href="#cb57-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-181"><a href="#cb57-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-182"><a href="#cb57-182" aria-hidden="true" tabindex="-1"></a>Ahora podemos decir que para un aumento de una unidad en gpa, las probabilidades de ser admitido en la escuela de postgrado (versus no ser admitido) aumentan en un factor de 2.23.</span>
<span id="cb57-183"><a href="#cb57-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-184"><a href="#cb57-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-185"><a href="#cb57-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-186"><a href="#cb57-186" aria-hidden="true" tabindex="-1"></a>También puede usar las probabilidades pronosticadas para ayudarlo a comprender el modelo. Las probabilidades pronosticadas se pueden calcular para variables  predictoras tanto categóricas como continuas. Para crear probabilidades pronosticadas, primero necesitamos crear un nuevo marco de datos con los valores que queremos que las variables independientes adopten para crear nuestras predicciones.</span>
<span id="cb57-187"><a href="#cb57-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-188"><a href="#cb57-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-191"><a href="#cb57-191" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-192"><a href="#cb57-192" aria-hidden="true" tabindex="-1"></a>newdata1 <span class="ot">&lt;-</span> <span class="fu">with</span>(mydata, <span class="fu">data.frame</span>(<span class="at">gre =</span> <span class="fu">mean</span>(gre), <span class="at">gpa =</span> <span class="fu">mean</span>(gpa), <span class="at">rank =</span> <span class="fu">factor</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>)))</span>
<span id="cb57-193"><a href="#cb57-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-194"><a href="#cb57-194" aria-hidden="true" tabindex="-1"></a>newdata1<span class="sc">$</span>rankP <span class="ot">&lt;-</span> <span class="fu">predict</span>(mylogit, <span class="at">newdata =</span> newdata1, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb57-195"><a href="#cb57-195" aria-hidden="true" tabindex="-1"></a>newdata1</span>
<span id="cb57-196"><a href="#cb57-196" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb57-197"><a href="#cb57-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-198"><a href="#cb57-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-199"><a href="#cb57-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-200"><a href="#cb57-200" aria-hidden="true" tabindex="-1"></a>En el resultado anterior, vemos que la probabilidad prevista de ser aceptado en un programa de postgrado es de 0.52 para estudiantes de las instituciones de pregrado de mayor prestigio (rango = 1) y 0.18 para estudiantes de las instituciones de menor rango (rango = 4), con gre y gpa por sus valores medios. Podemos hacer algo muy similar para crear una tabla de probabilidades predichas que varíe el valor de gre y rank. </span>
<span id="cb57-201"><a href="#cb57-201" aria-hidden="true" tabindex="-1"></a>Vamos a trazarlos, por lo que crearemos 100 valores de gre entre 200 y 800, en cada valor de rango (es decir, 1, 2, 3 y 4).</span>
<span id="cb57-202"><a href="#cb57-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-203"><a href="#cb57-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-204"><a href="#cb57-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-205"><a href="#cb57-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-208"><a href="#cb57-208" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-209"><a href="#cb57-209" aria-hidden="true" tabindex="-1"></a>newdata2 <span class="ot">&lt;-</span> <span class="fu">with</span>(mydata, <span class="fu">data.frame</span>(<span class="at">gre =</span> <span class="fu">rep</span>(<span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">200</span>, <span class="at">to =</span> <span class="dv">800</span>, <span class="at">length.out =</span> <span class="dv">100</span>),<span class="dv">4</span>), </span>
<span id="cb57-210"><a href="#cb57-210" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">gpa =</span> <span class="fu">mean</span>(gpa), <span class="at">rank =</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">each =</span> <span class="dv">100</span>))))</span>
<span id="cb57-211"><a href="#cb57-211" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb57-212"><a href="#cb57-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-213"><a href="#cb57-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-214"><a href="#cb57-214" aria-hidden="true" tabindex="-1"></a>El código para generar las probabilidades predichas (la primera línea a continuación) es el mismo que antes, excepto que también vamos a pedir errores estándar para que podamos trazar un intervalo de confianza. Obtenemos las estimaciones en la escala del enlace y transformamos los valores pronosticados y los límites de confianza en probabilidades.</span>
<span id="cb57-215"><a href="#cb57-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-216"><a href="#cb57-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-217"><a href="#cb57-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-220"><a href="#cb57-220" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-221"><a href="#cb57-221" aria-hidden="true" tabindex="-1"></a>newdata3 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(newdata2, <span class="fu">predict</span>(mylogit, <span class="at">newdata =</span> newdata2, <span class="at">type =</span> <span class="st">"link"</span>,</span>
<span id="cb57-222"><a href="#cb57-222" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">se =</span> <span class="cn">TRUE</span>))</span>
<span id="cb57-223"><a href="#cb57-223" aria-hidden="true" tabindex="-1"></a>newdata3 <span class="ot">&lt;-</span> <span class="fu">within</span>(newdata3, {</span>
<span id="cb57-224"><a href="#cb57-224" aria-hidden="true" tabindex="-1"></a>  PredictedProb <span class="ot">&lt;-</span> <span class="fu">plogis</span>(fit)</span>
<span id="cb57-225"><a href="#cb57-225" aria-hidden="true" tabindex="-1"></a>  LL <span class="ot">&lt;-</span> <span class="fu">plogis</span>(fit <span class="sc">-</span> (<span class="fl">1.96</span> <span class="sc">*</span> se.fit))</span>
<span id="cb57-226"><a href="#cb57-226" aria-hidden="true" tabindex="-1"></a>  UL <span class="ot">&lt;-</span> <span class="fu">plogis</span>(fit <span class="sc">+</span> (<span class="fl">1.96</span> <span class="sc">*</span> se.fit))</span>
<span id="cb57-227"><a href="#cb57-227" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb57-228"><a href="#cb57-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-229"><a href="#cb57-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-230"><a href="#cb57-230" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(newdata3)</span>
<span id="cb57-231"><a href="#cb57-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-232"><a href="#cb57-232" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb57-233"><a href="#cb57-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-234"><a href="#cb57-234" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(newdata3, <span class="fu">aes</span>(<span class="at">x =</span> gre, <span class="at">y =</span> PredictedProb)) <span class="sc">+</span> </span>
<span id="cb57-235"><a href="#cb57-235" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> LL,<span class="at">ymax =</span> UL, <span class="at">fill =</span> rank), <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb57-236"><a href="#cb57-236" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">colour =</span> rank),<span class="at">size =</span> <span class="dv">1</span>)</span>
<span id="cb57-237"><a href="#cb57-237" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb57-238"><a href="#cb57-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-239"><a href="#cb57-239" aria-hidden="true" tabindex="-1"></a><span class="fu">## Hosmer-Lemeshow</span></span>
<span id="cb57-240"><a href="#cb57-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-241"><a href="#cb57-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-244"><a href="#cb57-244" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-245"><a href="#cb57-245" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ResourceSelection)</span>
<span id="cb57-246"><a href="#cb57-246" aria-hidden="true" tabindex="-1"></a><span class="fu">hoslem.test</span>(mylogit<span class="sc">$</span>y,<span class="fu">fitted</span>(mylogit))</span>
<span id="cb57-247"><a href="#cb57-247" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb57-248"><a href="#cb57-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-249"><a href="#cb57-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-250"><a href="#cb57-250" aria-hidden="true" tabindex="-1"></a>No rechazo Ho, indicando que no hay evidencia de mal ajuste. Esto es bueno, ya que aquí sabemos que el modelo está correctamente especificado. </span>
<span id="cb57-251"><a href="#cb57-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-252"><a href="#cb57-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-253"><a href="#cb57-253" aria-hidden="true" tabindex="-1"></a><span class="fu">## Modelo Probit</span></span>
<span id="cb57-254"><a href="#cb57-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-255"><a href="#cb57-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-258"><a href="#cb57-258" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-259"><a href="#cb57-259" aria-hidden="true" tabindex="-1"></a><span class="co"># MODELO PROBIT</span></span>
<span id="cb57-260"><a href="#cb57-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-261"><a href="#cb57-261" aria-hidden="true" tabindex="-1"></a>myprobit <span class="ot">&lt;-</span> <span class="fu">glm</span>(admit <span class="sc">~</span> gre <span class="sc">+</span> gpa <span class="sc">+</span> rank, <span class="at">data =</span> mydata, <span class="at">family =</span>  <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"probit"</span>))</span>
<span id="cb57-262"><a href="#cb57-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-263"><a href="#cb57-263" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(myprobit)</span>
<span id="cb57-264"><a href="#cb57-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-265"><a href="#cb57-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-266"><a href="#cb57-266" aria-hidden="true" tabindex="-1"></a><span class="co">#Hosmer-Lemeshow</span></span>
<span id="cb57-267"><a href="#cb57-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-268"><a href="#cb57-268" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ResourceSelection)</span>
<span id="cb57-269"><a href="#cb57-269" aria-hidden="true" tabindex="-1"></a><span class="fu">hoslem.test</span>(myprobit<span class="sc">$</span>y,<span class="fu">fitted</span>(myprobit))</span>
<span id="cb57-270"><a href="#cb57-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-271"><a href="#cb57-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-272"><a href="#cb57-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-273"><a href="#cb57-273" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparación de Modelos</span></span>
<span id="cb57-274"><a href="#cb57-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-275"><a href="#cb57-275" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(memisc)</span>
<span id="cb57-276"><a href="#cb57-276" aria-hidden="true" tabindex="-1"></a><span class="fu">mtable</span>(myprobit, mylogit)</span>
<span id="cb57-277"><a href="#cb57-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-278"><a href="#cb57-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-279"><a href="#cb57-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-280"><a href="#cb57-280" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(marginaleffects)</span>
<span id="cb57-281"><a href="#cb57-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-282"><a href="#cb57-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-283"><a href="#cb57-283" aria-hidden="true" tabindex="-1"></a><span class="fu">avg_slopes</span>(mylogit)</span>
<span id="cb57-284"><a href="#cb57-284" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb57-285"><a href="#cb57-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-286"><a href="#cb57-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-287"><a href="#cb57-287" aria-hidden="true" tabindex="-1"></a>Esto me permite cuantificar el cambio promedio en la probabilidad de admisión (admit) asociado con cambios unitarios en las variables explicativas (gre, gpa y rank), proporcionando una interpretación más clara de los efectos directos de cada variable en la probabilidad de admisión.</span>
<span id="cb57-288"><a href="#cb57-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-289"><a href="#cb57-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-290"><a href="#cb57-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-291"><a href="#cb57-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-292"><a href="#cb57-292" aria-hidden="true" tabindex="-1"></a>En este bloque de código, estoy ajustando un modelo de regresión logística (logit) para predecir la probabilidad de admisión (admit) en función del puntaje GRE, el GPA, el rango de la institución de pregrado (rank) y la interacción entre GRE y GPA. </span>
<span id="cb57-293"><a href="#cb57-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-294"><a href="#cb57-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-295"><a href="#cb57-295" aria-hidden="true" tabindex="-1"></a>Luego, utilizo la función plot_slopes para visualizar cómo varía la pendiente de la probabilidad de admisión en función de GRE condicionado al GPA y viceversa. Esto me permite entender mejor la interacción entre GRE y GPA y su efecto en la probabilidad de admisión.</span>
<span id="cb57-296"><a href="#cb57-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-297"><a href="#cb57-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-298"><a href="#cb57-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-301"><a href="#cb57-301" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-302"><a href="#cb57-302" aria-hidden="true" tabindex="-1"></a>mylogit2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(admit <span class="sc">~</span> gre <span class="sc">+</span> gpa <span class="sc">+</span> gre<span class="sc">*</span>gpa <span class="sc">+</span> rank, <span class="at">data =</span> mydata, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb57-303"><a href="#cb57-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-304"><a href="#cb57-304" aria-hidden="true" tabindex="-1"></a><span class="co"># Graficar la pendiente del efecto de GRE en la probabilidad de admisión condicionada al GPA</span></span>
<span id="cb57-305"><a href="#cb57-305" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_slopes</span>(mylogit2, <span class="at">variables=</span><span class="st">"gre"</span>, <span class="at">condition =</span> <span class="st">"gpa"</span>)</span>
<span id="cb57-306"><a href="#cb57-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-307"><a href="#cb57-307" aria-hidden="true" tabindex="-1"></a><span class="co"># Graficar la pendiente del efecto de GPA en la probabilidad de admisión condicionada al GRE</span></span>
<span id="cb57-308"><a href="#cb57-308" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_slopes</span>(mylogit2, <span class="at">variables=</span><span class="st">"gpa"</span>, <span class="at">condition =</span> <span class="st">"gre"</span>)</span>
<span id="cb57-309"><a href="#cb57-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-310"><a href="#cb57-310" aria-hidden="true" tabindex="-1"></a><span class="co"># Ahora con la variable rank</span></span>
<span id="cb57-311"><a href="#cb57-311" aria-hidden="true" tabindex="-1"></a>mylogit2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(admit <span class="sc">~</span> gre <span class="sc">+</span> gpa <span class="sc">+</span> rank<span class="sc">*</span>gpa <span class="sc">+</span> rank, <span class="at">data =</span> mydata, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb57-312"><a href="#cb57-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-313"><a href="#cb57-313" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_slopes</span>(mylogit2, <span class="at">variables=</span><span class="st">"rank"</span>, <span class="at">condition =</span> <span class="st">"gpa"</span>)<span class="sc">+</span></span>
<span id="cb57-314"><a href="#cb57-314" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lims</span>(<span class="at">y=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb57-315"><a href="#cb57-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-316"><a href="#cb57-316" aria-hidden="true" tabindex="-1"></a>mylogit2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(admit <span class="sc">~</span> gre <span class="sc">+</span> gpa <span class="sc">+</span> rank<span class="sc">*</span>gre <span class="sc">+</span> rank, <span class="at">data =</span> mydata, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb57-317"><a href="#cb57-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-318"><a href="#cb57-318" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_slopes</span>(mylogit2, <span class="at">variables=</span><span class="st">"rank"</span>, <span class="at">condition =</span> <span class="st">"gre"</span>)<span class="sc">+</span></span>
<span id="cb57-319"><a href="#cb57-319" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lims</span>(<span class="at">y=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb57-320"><a href="#cb57-320" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb57-321"><a href="#cb57-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-322"><a href="#cb57-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-323"><a href="#cb57-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-324"><a href="#cb57-324" aria-hidden="true" tabindex="-1"></a><span class="fu">## Modelo Multinomial</span></span>
<span id="cb57-325"><a href="#cb57-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-326"><a href="#cb57-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-327"><a href="#cb57-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-328"><a href="#cb57-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-329"><a href="#cb57-329" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Ejemplo 1. Las elecciones ocupacionales de las personas pueden verse influenciadas por las ocupaciones de sus padres y su propio nivel educativo. Podemos estudiar la relación entre la elección de ocupación y el nivel educativo y la ocupación del padre. Las elecciones ocupacionales serán la variable de resultado que consta de categorías de ocupaciones.</span></span>
<span id="cb57-330"><a href="#cb57-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-331"><a href="#cb57-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-332"><a href="#cb57-332" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Ejemplo 2. Un biólogo puede estar interesado en las elecciones de alimentos que hacen los caimanes. Los caimanes adultos pueden tener preferencias diferentes a las de los jóvenes. La variable de resultado aquí serán los tipos de alimentos, y las variables predictoras podrían ser el tamaño de los caimanes y otras variables ambientales.</span></span>
<span id="cb57-333"><a href="#cb57-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-334"><a href="#cb57-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-335"><a href="#cb57-335" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Ejemplo 3. Los estudiantes que ingresan a la escuela secundaria eligen programas entre programa general, programa vocacional y programa académico. Su elección podría modelarse utilizando su puntaje de escritura y su estatus económico social.</span></span>
<span id="cb57-336"><a href="#cb57-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-337"><a href="#cb57-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-338"><a href="#cb57-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-339"><a href="#cb57-339" aria-hidden="true" tabindex="-1"></a>El conjunto de datos contiene variables sobre 200 estudiantes. La variable de resultado es 'prog' tipo de programa. Las variables predictoras son el status socioeconómico, 'ses' una variable categórica de tres niveles, y la puntuación de escritura, 'write' una variable continua. </span>
<span id="cb57-340"><a href="#cb57-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-341"><a href="#cb57-341" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-342"><a href="#cb57-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-345"><a href="#cb57-345" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-346"><a href="#cb57-346" aria-hidden="true" tabindex="-1"></a><span class="do">######################################</span></span>
<span id="cb57-347"><a href="#cb57-347" aria-hidden="true" tabindex="-1"></a><span class="co">#Modelo Multinomial</span></span>
<span id="cb57-348"><a href="#cb57-348" aria-hidden="true" tabindex="-1"></a><span class="do">######################################</span></span>
<span id="cb57-349"><a href="#cb57-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-350"><a href="#cb57-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-351"><a href="#cb57-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-352"><a href="#cb57-352" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(foreign) </span>
<span id="cb57-353"><a href="#cb57-353" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nnet) </span>
<span id="cb57-354"><a href="#cb57-354" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2) </span>
<span id="cb57-355"><a href="#cb57-355" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span>
<span id="cb57-356"><a href="#cb57-356" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-357"><a href="#cb57-357" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-358"><a href="#cb57-358" aria-hidden="true" tabindex="-1"></a>ml  <span class="ot">&lt;-</span>  <span class="fu">read.dta</span> ( <span class="st">"Datos/hsb.dta"</span> )</span>
<span id="cb57-359"><a href="#cb57-359" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-360"><a href="#cb57-360" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ml)</span>
<span id="cb57-361"><a href="#cb57-361" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb57-362"><a href="#cb57-362" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-363"><a href="#cb57-363" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-364"><a href="#cb57-364" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-365"><a href="#cb57-365" aria-hidden="true" tabindex="-1"></a>A continuación utilizamos la función multinom del nnet paquete para estimar un modelo de regresión logística multinomial.  Hay otras funciones en otros paquetes de R capaces de realizar regresión multinomial.</span>
<span id="cb57-366"><a href="#cb57-366" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-367"><a href="#cb57-367" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-368"><a href="#cb57-368" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-369"><a href="#cb57-369" aria-hidden="true" tabindex="-1"></a>Primero, debemos elegir el nivel de nuestro resultado que deseamos utilizar como línea de base y especificarlo en la función relevel. Luego, ejecutamos nuestro modelo usando multinom. El paquete multinom no incluye el cálculo del valor p para los coeficientes de regresión, por lo que calculamos los valores p utilizando las pruebas de Wald (aquí pruebas z).</span>
<span id="cb57-370"><a href="#cb57-370" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-371"><a href="#cb57-371" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-372"><a href="#cb57-372" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-373"><a href="#cb57-373" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-374"><a href="#cb57-374" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-377"><a href="#cb57-377" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-378"><a href="#cb57-378" aria-hidden="true" tabindex="-1"></a>ml<span class="sc">$</span>prog2 <span class="ot">&lt;-</span> <span class="fu">relevel</span>(ml<span class="sc">$</span>prog, <span class="at">ref =</span> <span class="st">"academic"</span>)</span>
<span id="cb57-379"><a href="#cb57-379" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-380"><a href="#cb57-380" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> <span class="fu">multinom</span>(prog2 <span class="sc">~</span> ses <span class="sc">+</span> write, <span class="at">data =</span> ml)</span>
<span id="cb57-381"><a href="#cb57-381" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-382"><a href="#cb57-382" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(test)</span>
<span id="cb57-383"><a href="#cb57-383" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-384"><a href="#cb57-384" aria-hidden="true" tabindex="-1"></a><span class="co"># Valores z</span></span>
<span id="cb57-385"><a href="#cb57-385" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">summary</span>(test)<span class="sc">$</span>coefficients<span class="sc">/</span><span class="fu">summary</span>(test)<span class="sc">$</span>standard.errors</span>
<span id="cb57-386"><a href="#cb57-386" aria-hidden="true" tabindex="-1"></a>z</span>
<span id="cb57-387"><a href="#cb57-387" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-388"><a href="#cb57-388" aria-hidden="true" tabindex="-1"></a><span class="co"># Valores p</span></span>
<span id="cb57-389"><a href="#cb57-389" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(z), <span class="dv">0</span>, <span class="dv">1</span>)) <span class="sc">*</span> <span class="dv">2</span></span>
<span id="cb57-390"><a href="#cb57-390" aria-hidden="true" tabindex="-1"></a>p</span>
<span id="cb57-391"><a href="#cb57-391" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-392"><a href="#cb57-392" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-393"><a href="#cb57-393" aria-hidden="true" tabindex="-1"></a><span class="co"># Algunas interpretaciones del modelo "test"</span></span>
<span id="cb57-394"><a href="#cb57-394" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-395"><a href="#cb57-395" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(test)</span>
<span id="cb57-396"><a href="#cb57-396" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb57-397"><a href="#cb57-397" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-398"><a href="#cb57-398" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-399"><a href="#cb57-399" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-400"><a href="#cb57-400" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-401"><a href="#cb57-401" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Un aumento de una unidad en la variable write se asocia con una disminución en las probabilidades logarítmicas de estar en un programa general versus un programa académico en una cantidad de 0,058.</span>
<span id="cb57-402"><a href="#cb57-402" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-403"><a href="#cb57-403" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Un aumento de una unidad en la variable write se asocia con la disminución en las probabilidades logarítmicas de estar en un programa vocacional versus un programa académico. por la cantidad de .1136</span>
<span id="cb57-404"><a href="#cb57-404" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-405"><a href="#cb57-405" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Las probabilidades logarítmicas de estar en un programa general frente a un programa académico disminuirán en 1.163 si se pasa de ses="low"a ses="high"</span>
<span id="cb57-406"><a href="#cb57-406" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-407"><a href="#cb57-407" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Las probabilidades logarítmicas de estar en un programa general frente a un programa académico disminuirán en 0.533 si se pasa de ses="low"a ses="middle", aunque este coeficiente no es significativo.</span>
<span id="cb57-408"><a href="#cb57-408" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-409"><a href="#cb57-409" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Las probabilidades logarítmicas de estar en un programa vocacional frente a un programa académico disminuirán en 0.983 si se pasa de ses="low"a ses="high"</span>
<span id="cb57-410"><a href="#cb57-410" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-411"><a href="#cb57-411" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Las probabilidades logarítmicas de estar en un programa vocacional frente a un programa académico aumentarán en 0.291 si se pasa de ses="low"a ses="middle",aunque este coeficiente no es significativo.</span>
<span id="cb57-412"><a href="#cb57-412" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-413"><a href="#cb57-413" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-414"><a href="#cb57-414" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-415"><a href="#cb57-415" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-418"><a href="#cb57-418" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-419"><a href="#cb57-419" aria-hidden="true" tabindex="-1"></a><span class="co"># Odds ratio</span></span>
<span id="cb57-420"><a href="#cb57-420" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-421"><a href="#cb57-421" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-422"><a href="#cb57-422" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(test))</span>
<span id="cb57-423"><a href="#cb57-423" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-424"><a href="#cb57-424" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-425"><a href="#cb57-425" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-426"><a href="#cb57-426" aria-hidden="true" tabindex="-1"></a><span class="co"># Probabilidades predichas</span></span>
<span id="cb57-427"><a href="#cb57-427" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-428"><a href="#cb57-428" aria-hidden="true" tabindex="-1"></a>pp <span class="ot">&lt;-</span> <span class="fu">fitted</span>(test)</span>
<span id="cb57-429"><a href="#cb57-429" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-430"><a href="#cb57-430" aria-hidden="true" tabindex="-1"></a>pp</span>
<span id="cb57-431"><a href="#cb57-431" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb57-432"><a href="#cb57-432" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-433"><a href="#cb57-433" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-434"><a href="#cb57-434" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-435"><a href="#cb57-435" aria-hidden="true" tabindex="-1"></a>A continuación, si queremos examinar los cambios en la probabilidad predicha asociados con una de nuestras dos variables, podemos crear pequeños conjuntos de datos variando una variable mientras mantenemos la otra constante. </span>
<span id="cb57-436"><a href="#cb57-436" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-437"><a href="#cb57-437" aria-hidden="true" tabindex="-1"></a>Primero haremos esto manteniendo write su media y examinando las probabilidades predichas para cada nivel de ses.</span>
<span id="cb57-438"><a href="#cb57-438" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-439"><a href="#cb57-439" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-440"><a href="#cb57-440" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-441"><a href="#cb57-441" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-442"><a href="#cb57-442" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-445"><a href="#cb57-445" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-446"><a href="#cb57-446" aria-hidden="true" tabindex="-1"></a>dses <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">ses =</span> <span class="fu">c</span>(<span class="st">"low"</span>, <span class="st">"middle"</span>, <span class="st">"high"</span>), <span class="at">write =</span> <span class="fu">mean</span>(ml<span class="sc">$</span>write))</span>
<span id="cb57-447"><a href="#cb57-447" aria-hidden="true" tabindex="-1"></a>dses</span>
<span id="cb57-448"><a href="#cb57-448" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-449"><a href="#cb57-449" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(test, <span class="at">newdata =</span> dses, <span class="st">"probs"</span>)</span>
<span id="cb57-450"><a href="#cb57-450" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb57-451"><a href="#cb57-451" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-452"><a href="#cb57-452" aria-hidden="true" tabindex="-1"></a>Otra forma de entender el modelo es utilizando las probabilidades predichas para observar las probabilidades promediadas predichas para diferentes valores de la variable predictora continua write dentro de cada nivel de ses.</span>
<span id="cb57-453"><a href="#cb57-453" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-454"><a href="#cb57-454" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-455"><a href="#cb57-455" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-458"><a href="#cb57-458" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-459"><a href="#cb57-459" aria-hidden="true" tabindex="-1"></a>dwrite <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">ses =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"low"</span>, <span class="st">"middle"</span>, <span class="st">"high"</span>),</span>
<span id="cb57-460"><a href="#cb57-460" aria-hidden="true" tabindex="-1"></a>                               <span class="at">each =</span> <span class="dv">41</span>), <span class="at">write =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="dv">30</span><span class="sc">:</span><span class="dv">70</span>), <span class="dv">3</span>))</span>
<span id="cb57-461"><a href="#cb57-461" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-462"><a href="#cb57-462" aria-hidden="true" tabindex="-1"></a><span class="do">## almacene las probabilidades predichas para cada valor de ses</span></span>
<span id="cb57-463"><a href="#cb57-463" aria-hidden="true" tabindex="-1"></a>pp.write <span class="ot">&lt;-</span> <span class="fu">cbind</span>(dwrite, <span class="fu">predict</span>(test, <span class="at">newdata =</span> dwrite, <span class="at">type =</span> <span class="st">"probs"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>))</span>
<span id="cb57-464"><a href="#cb57-464" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-465"><a href="#cb57-465" aria-hidden="true" tabindex="-1"></a><span class="do">## calcular las probabilidades medias dentro de cada nivel de ses </span></span>
<span id="cb57-466"><a href="#cb57-466" aria-hidden="true" tabindex="-1"></a><span class="fu">by</span>(pp.write[, <span class="dv">3</span><span class="sc">:</span><span class="dv">5</span>], pp.write<span class="sc">$</span>ses, colMeans)</span>
<span id="cb57-467"><a href="#cb57-467" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-468"><a href="#cb57-468" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-469"><a href="#cb57-469" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-470"><a href="#cb57-470" aria-hidden="true" tabindex="-1"></a><span class="co"># Grafico probabilidades predichas</span></span>
<span id="cb57-471"><a href="#cb57-471" aria-hidden="true" tabindex="-1"></a><span class="co"># Pasar la base a formato long para utilizar ggplot</span></span>
<span id="cb57-472"><a href="#cb57-472" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-473"><a href="#cb57-473" aria-hidden="true" tabindex="-1"></a>lpp <span class="ot">&lt;-</span> <span class="fu">melt</span>(pp.write, <span class="at">id.vars =</span> <span class="fu">c</span>(<span class="st">"ses"</span>, <span class="st">"write"</span>), <span class="at">value.name =</span> <span class="st">"probability"</span>)</span>
<span id="cb57-474"><a href="#cb57-474" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-475"><a href="#cb57-475" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(lpp, <span class="fu">aes</span>(<span class="at">x =</span> write, <span class="at">y =</span> probability, <span class="at">colour =</span> ses)) <span class="sc">+</span></span>
<span id="cb57-476"><a href="#cb57-476" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb57-477"><a href="#cb57-477" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(variable <span class="sc">~</span> ., <span class="at">scales =</span> <span class="st">"free"</span>)</span>
<span id="cb57-478"><a href="#cb57-478" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-479"><a href="#cb57-479" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-480"><a href="#cb57-480" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(marginaleffects)</span>
<span id="cb57-481"><a href="#cb57-481" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-482"><a href="#cb57-482" aria-hidden="true" tabindex="-1"></a><span class="fu">avg_slopes</span>(test)</span>
<span id="cb57-483"><a href="#cb57-483" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-484"><a href="#cb57-484" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-485"><a href="#cb57-485" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-486"><a href="#cb57-486" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb57-487"><a href="#cb57-487" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-488"><a href="#cb57-488" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-489"><a href="#cb57-489" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-490"><a href="#cb57-490" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-491"><a href="#cb57-491" aria-hidden="true" tabindex="-1"></a>En este bloque de código, estoy calculando los efectos promedio marginales en un modelo multinomial para entender cómo las variables independientes ses (nivel socioeconómico) y write (puntuación de escritura) influyen en la probabilidad de estar en diferentes grupos de la variable dependiente (academic, general, vocation).</span>
<span id="cb57-492"><a href="#cb57-492" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-493"><a href="#cb57-493" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-494"><a href="#cb57-494" aria-hidden="true" tabindex="-1"></a>Estos resultados permiten interpretar el cambio promedio en la probabilidad de estar en cada grupo, condicionado a cambios en las variables independientes, proporcionando una comprensión detallada de los efectos específicos.</span>
<span id="cb57-495"><a href="#cb57-495" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-496"><a href="#cb57-496" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-497"><a href="#cb57-497" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-498"><a href="#cb57-498" aria-hidden="true" tabindex="-1"></a>**Resultados del modelo multinomial**</span>
<span id="cb57-499"><a href="#cb57-499" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-500"><a href="#cb57-500" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Group: academic</span></span>
<span id="cb57-501"><a href="#cb57-501" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-502"><a href="#cb57-502" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>ses: high - low (Estimate: 0.23181, Std. Error: 0.09367, z-value: 2.475, Pr(&gt;|z|): 0.0133)</span>
<span id="cb57-503"><a href="#cb57-503" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-504"><a href="#cb57-504" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Un nivel socioeconómico alto comparado con un nivel bajo aumenta la probabilidad de estar en el grupo 'academic' en 0.23181 unidades en la escala logit. Este efecto es estadísticamente significativo (p-valor = 0.0133).</span>
<span id="cb57-505"><a href="#cb57-505" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-506"><a href="#cb57-506" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>ses: middle - low (Estimate: 0.03576, Std. Error: 0.08406, z-value: 0.425, Pr(&gt;|z|): 0.6705) </span>
<span id="cb57-507"><a href="#cb57-507" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-508"><a href="#cb57-508" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Un nivel socioeconómico medio comparado con un nivel bajo tiene un efecto positivo muy pequeño y no significativo en la probabilidad de estar en el grupo 'academic'.</span>
<span id="cb57-509"><a href="#cb57-509" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-510"><a href="#cb57-510" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>write: dY/dX (Estimate: 0.01714, Std. Error: 0.00288, z-value: 5.959, Pr(&gt;|z|): &lt;0.001)</span>
<span id="cb57-511"><a href="#cb57-511" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-512"><a href="#cb57-512" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Un incremento en una unidad en la puntuación de escritura aumenta la probabilidad de estar en el grupo 'academic' en 0.01714. Este efecto es altamente significativo (p-valor &lt; 0.001).</span>
<span id="cb57-513"><a href="#cb57-513" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-514"><a href="#cb57-514" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Group: general</span></span>
<span id="cb57-515"><a href="#cb57-515" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-516"><a href="#cb57-516" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>ses: high - low (Estimate: -0.16006, Std. Error: 0.08686, z-value: -1.843, Pr(&gt;|z|): 0.0654)</span>
<span id="cb57-517"><a href="#cb57-517" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-518"><a href="#cb57-518" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Un nivel socioeconómico alto comparado con un nivel bajo disminuye la probabilidad de estar en el grupo 'general' en 0.16006 unidades en la escala logit. Este efecto es marginalmente significativo (p-valor = 0.0654).</span>
<span id="cb57-519"><a href="#cb57-519" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-520"><a href="#cb57-520" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>ses: middle - low (Estimate: -0.12447, Std. Error: 0.07993, z-value: -1.557, Pr(&gt;|z|): 0.1194)</span>
<span id="cb57-521"><a href="#cb57-521" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-522"><a href="#cb57-522" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Un nivel socioeconómico medio comparado con un nivel bajo tiene un efecto negativo y no significativo en la probabilidad de estar en el grupo 'general'.</span>
<span id="cb57-523"><a href="#cb57-523" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-524"><a href="#cb57-524" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>write: dY/dX (Estimate: -0.00283, Std. Error: 0.00282, z-value: -1.002, Pr(&gt;|z|): 0.3164)</span>
<span id="cb57-525"><a href="#cb57-525" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-526"><a href="#cb57-526" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Un incremento en una unidad en la puntuación de escritura disminuye la probabilidad de estar en el grupo 'general' en 0.00283. Este efecto no es significativo (p-valor = 0.3164).</span>
<span id="cb57-527"><a href="#cb57-527" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-528"><a href="#cb57-528" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Group: vocation</span></span>
<span id="cb57-529"><a href="#cb57-529" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-530"><a href="#cb57-530" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>ses: high - low (Estimate: -0.07175, Std. Error: 0.07432, z-value: -0.965, Pr(&gt;|z|): 0.3343)</span>
<span id="cb57-531"><a href="#cb57-531" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-532"><a href="#cb57-532" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Un nivel socioeconómico alto comparado con un nivel bajo disminuye la probabilidad de estar en el grupo 'vocation' en 0.07175 unidades en la escala logit. Este efecto no es significativo (p-valor = 0.3343).</span>
<span id="cb57-533"><a href="#cb57-533" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-534"><a href="#cb57-534" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>ses: middle - low (Estimate: 0.08870, Std. Error: 0.06982, z-value: 1.270, Pr(&gt;|z|): 0.2039)</span>
<span id="cb57-535"><a href="#cb57-535" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-536"><a href="#cb57-536" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Un nivel socioeconómico medio comparado con un nivel bajo aumenta la probabilidad de estar en el grupo 'vocation' en 0.08870 unidades en la escala logit. Este efecto no es significativo (p-valor = 0.2039).</span>
<span id="cb57-537"><a href="#cb57-537" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-538"><a href="#cb57-538" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>write: dY/dX (Estimate: -0.01431, Std. Error: 0.00251, z-value: -5.698, Pr(&gt;|z|): &lt;0.001)</span>
<span id="cb57-539"><a href="#cb57-539" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-540"><a href="#cb57-540" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Un incremento en una unidad en la puntuación de escritura disminuye la probabilidad de estar en el grupo 'vocation' en 0.01431. Este efecto es altamente significativo (p-valor &lt; 0.001).</span>
<span id="cb57-541"><a href="#cb57-541" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-542"><a href="#cb57-542" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-543"><a href="#cb57-543" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-544"><a href="#cb57-544" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-545"><a href="#cb57-545" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-546"><a href="#cb57-546" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-547"><a href="#cb57-547" aria-hidden="true" tabindex="-1"></a><span class="fu"># Taller</span></span>
<span id="cb57-548"><a href="#cb57-548" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-549"><a href="#cb57-549" aria-hidden="true" tabindex="-1"></a><span class="fu">## Objetivo</span></span>
<span id="cb57-550"><a href="#cb57-550" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-551"><a href="#cb57-551" aria-hidden="true" tabindex="-1"></a>Modelar una elección con ≥3 categorías nominales y responder preguntas de política/gestión con probabilidades predichas, efectos marginales, etc.</span>
<span id="cb57-552"><a href="#cb57-552" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-553"><a href="#cb57-553" aria-hidden="true" tabindex="-1"></a><span class="fu">## Fuentes sugeridas</span></span>
<span id="cb57-554"><a href="#cb57-554" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-555"><a href="#cb57-555" aria-hidden="true" tabindex="-1"></a>World Bank Data (DataBank), OECD Data, Our World in Data, UN Data, FAOSTAT, IMF Data.</span>
<span id="cb57-556"><a href="#cb57-556" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-557"><a href="#cb57-557" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Elijan un dataset con ≥ 300 observaciones (país-año, hogares, empresas, etc) y variables claras. Importante que la frecuencia en las clases sea balanceada.</span></span>
<span id="cb57-558"><a href="#cb57-558" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-559"><a href="#cb57-559" aria-hidden="true" tabindex="-1"></a><span class="fu">## Ejemplos de preguntas</span></span>
<span id="cb57-560"><a href="#cb57-560" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-561"><a href="#cb57-561" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-562"><a href="#cb57-562" aria-hidden="true" tabindex="-1"></a>**Transporte**</span>
<span id="cb57-563"><a href="#cb57-563" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-564"><a href="#cb57-564" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;¿Qué factores explican elegir bus/metro/bici/auto?</span></span>
<span id="cb57-565"><a href="#cb57-565" aria-hidden="true" tabindex="-1"></a><span class="at">Y: modo. X: tiempo, costo, clima, ingresos. Contrafactual: −10% en tiempo del metro → ¿nuevos shares?</span></span>
<span id="cb57-566"><a href="#cb57-566" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-567"><a href="#cb57-567" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;¿Cómo cambian las elecciones Uber/taxi/bus según hora del día?</span></span>
<span id="cb57-568"><a href="#cb57-568" aria-hidden="true" tabindex="-1"></a><span class="at">Y: servicio. X: hora pico, tarifa dinámica, lluvia. Contrafactual: +15% tarifa Uber.</span></span>
<span id="cb57-569"><a href="#cb57-569" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-570"><a href="#cb57-570" aria-hidden="true" tabindex="-1"></a>**Educación**</span>
<span id="cb57-571"><a href="#cb57-571" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-572"><a href="#cb57-572" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;¿Qué perfila la elección de programa académico/general/vocacional?</span></span>
<span id="cb57-573"><a href="#cb57-573" aria-hidden="true" tabindex="-1"></a><span class="at">Y: programa. X: puntaje, SES, género, escuela previa. Contrafactual: +10 puntos en “write”.</span></span>
<span id="cb57-574"><a href="#cb57-574" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-575"><a href="#cb57-575" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;¿Qué determina escoger universidad pública/privada/externa?</span></span>
<span id="cb57-576"><a href="#cb57-576" aria-hidden="true" tabindex="-1"></a><span class="at">Y: tipo de institución. X: ingreso hogar, becas, distancia. Contrafactual: beca del 50% en privada.</span></span>
<span id="cb57-577"><a href="#cb57-577" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-578"><a href="#cb57-578" aria-hidden="true" tabindex="-1"></a>**Salud**</span>
<span id="cb57-579"><a href="#cb57-579" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-580"><a href="#cb57-580" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;¿Qué lleva a elegir EPS A/EPS B/privado?</span></span>
<span id="cb57-581"><a href="#cb57-581" aria-hidden="true" tabindex="-1"></a><span class="at">Y: proveedor. X: prima, tiempo de espera, edad, crónicos. Contrafactual: reducir espera en EPS B a 20 min.</span></span>
<span id="cb57-582"><a href="#cb57-582" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-583"><a href="#cb57-583" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;En urgencias, ¿por qué eligen clínica X/clínica Y/hospital?</span></span>
<span id="cb57-584"><a href="#cb57-584" aria-hidden="true" tabindex="-1"></a><span class="at">Y: centro. X: distancia, saturación, seguro. Contrafactual: abrir nueva sede de la clínica X más cerca.</span></span>
<span id="cb57-585"><a href="#cb57-585" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-586"><a href="#cb57-586" aria-hidden="true" tabindex="-1"></a>**Finanzas**</span>
<span id="cb57-587"><a href="#cb57-587" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-588"><a href="#cb57-588" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;¿Qué define elegir tarjeta débito/crédito/fintech para pagar?</span></span>
<span id="cb57-589"><a href="#cb57-589" aria-hidden="true" tabindex="-1"></a><span class="at">Y: método. X: ingresos, comisiones, cashback, edad. Contrafactual: +2% cashback en fintech.</span></span>
<span id="cb57-590"><a href="#cb57-590" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-591"><a href="#cb57-591" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;¿Qué influye en tipo de cuenta (básica/premium/pyme)?</span></span>
<span id="cb57-592"><a href="#cb57-592" aria-hidden="true" tabindex="-1"></a><span class="at">Y: producto. X: tarifas, uso mensual, score. Contrafactual: eximir cuota de manejo en “premium”.</span></span>
<span id="cb57-593"><a href="#cb57-593" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-594"><a href="#cb57-594" aria-hidden="true" tabindex="-1"></a>**Consumo/Marketing**</span>
<span id="cb57-595"><a href="#cb57-595" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-596"><a href="#cb57-596" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;¿Qué explica elegir marca A/B/C de café?</span></span>
<span id="cb57-597"><a href="#cb57-597" aria-hidden="true" tabindex="-1"></a><span class="at">Y: marca. X: precio, sello orgánico, origen, reseñas. Contrafactual: certificación orgánica para B.</span></span>
<span id="cb57-598"><a href="#cb57-598" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-599"><a href="#cb57-599" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;Delivery: Rappi/UberEats/DidiFood</span></span>
<span id="cb57-600"><a href="#cb57-600" aria-hidden="true" tabindex="-1"></a><span class="at">Y: plataforma. X: costo envío, tiempo, cupones, rating. Contrafactual: cupón 30% en Rappi.</span></span>
<span id="cb57-601"><a href="#cb57-601" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-602"><a href="#cb57-602" aria-hidden="true" tabindex="-1"></a>**Energía/Ambiente**</span>
<span id="cb57-603"><a href="#cb57-603" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-604"><a href="#cb57-604" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;¿Qué determina el combustible de cocina gas/electricidad/biomasa?</span></span>
<span id="cb57-605"><a href="#cb57-605" aria-hidden="true" tabindex="-1"></a><span class="at">Y: combustible. X: ingreso, subsidio, zona, precio relativo. Contrafactual: bajar precio de electricidad 15%.</span></span>
<span id="cb57-606"><a href="#cb57-606" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-607"><a href="#cb57-607" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-608"><a href="#cb57-608" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-609"><a href="#cb57-609" aria-hidden="true" tabindex="-1"></a><span class="fu">## Pasos (mínimos)</span></span>
<span id="cb57-610"><a href="#cb57-610" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-611"><a href="#cb57-611" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Pregunta y alternativas</span>
<span id="cb57-612"><a href="#cb57-612" aria-hidden="true" tabindex="-1"></a>Define la decisión a modelar y las categorías nominales (≥3). Explica por qué no es binario ni ordinal. Fija la categoría base.</span>
<span id="cb57-613"><a href="#cb57-613" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-614"><a href="#cb57-614" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Datos y limpieza</span>
<span id="cb57-615"><a href="#cb57-615" aria-hidden="true" tabindex="-1"></a>Fuente, tamaño (≥300 obs. sugerido), definiciones, recodificaciones a factor, outliers/NA, y una tabla de frecuencias por categoría.</span>
<span id="cb57-616"><a href="#cb57-616" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-617"><a href="#cb57-617" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Modelo (MNL)</span>
<span id="cb57-618"><a href="#cb57-618" aria-hidden="true" tabindex="-1"></a>Especifica y ~ x1 + x2 + … (incluye 1 interacción simple si tiene sentido). Explica la plausibilidad del IIA (antes de estimar): ¿hay “clones”?</span>
<span id="cb57-619"><a href="#cb57-619" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-620"><a href="#cb57-620" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Estimación y lectura</span>
<span id="cb57-621"><a href="#cb57-621" aria-hidden="true" tabindex="-1"></a>Ajusta con nnet::multinom. Reporta coeficientes, odds ratios (OR) y p-valores (Wald). Interpreta por categoría vs. baseline.</span>
<span id="cb57-622"><a href="#cb57-622" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-623"><a href="#cb57-623" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>Validación/diagnóstico</span>
<span id="cb57-624"><a href="#cb57-624" aria-hidden="true" tabindex="-1"></a>Pseudo-R², log-likelihood, tasa de acierto (matriz de confusión).</span>
<span id="cb57-625"><a href="#cb57-625" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-626"><a href="#cb57-626" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>Predicciones</span>
<span id="cb57-627"><a href="#cb57-627" aria-hidden="true" tabindex="-1"></a>Construye perfiles y reporta probabilidades predichas P(y=j | x); grafica P vs. un predictor clave con facetas por categoría.</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>